import React, { createContext, useContext, ReactNode } from 'react';
import { useAppContext } from '../../../../../context/app-context';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, values?: Record<string, any>) => string;
}

const translations = {
  en: {
    welcome: 'Welcome to Wise',
    recruitment: 'Recruitment',
    analytics: 'Analytics',
    jobRequisition: 'Job Requisition',
    candidate: 'Candidate',
    interview: 'Interview',
    offer: 'Offer',
    onboarding: 'Onboarding',
    careersPortalSetup: 'Careers Portal Setup',
    contentComingSoon: 'Content coming soon',
    groupByStage: 'Group by Stage',
    groupByJob: 'Group by Job',
    kanbanView: 'Kanban View',
    listView: 'List View',
    filters: 'Filters',
    source: 'Source',
    aiScore: 'AI Score',
    nationality: 'Nationality',
    stage: 'Stage',
    new: 'New',
    shortlisted: 'Shortlisted',
    interviewed: 'Interviewed',
    offered: 'Offered',
    hired: 'Hired',
    rejected: 'Rejected',
    addCandidate: 'Add Candidate',
    searchLinkedIn: 'Search LinkedIn',
    bulkActions: 'Bulk Actions',
    moveToStage: 'Move to Stage',
    bulkMoveDescription: 'Move selected candidates to another stage',
    addTags: 'Add Tags',
    bulkTagsDescription: 'Add tags to selected candidates',
    sendEmail: 'Send Email',
    bulkEmailDescription: 'Send email to selected candidates',
    exportCandidates: 'Export Candidates',
    bulkExportDescription: 'Export selected candidates to CSV',
    deleteCandidates: 'Delete Candidates',
    bulkDeleteDescription: 'Delete selected candidates permanently',
    noCandidate: 'No candidates found',
    dragToMove: 'Drag to move',
    name: 'Name',
    aiScore: 'AI Match Score',
    source: 'Source',
    stage: 'Stage',
    dateAdded: 'Date Added',
    actions: 'Actions',
    referredBy: 'Referred by',
    matchScore: 'Match Score',
    stage1: 'Stage 1',
    stage2: 'Stage 2',
    stage3: 'Stage 3',
    pageInfo: 'Page {current} of {total}',
    linkedInSearchInfo: 'LinkedIn Search Info',
    searchForCandidates: 'Search for Candidates',
    apply: 'Apply',
    uploadCv: 'Upload CV',
    emailTemplateInfo: 'Email Template Info',
    findOnLinkedIn: 'Find on LinkedIn',
    findSimilarCandidates: 'Find Similar Candidates',
    groupByStage: 'Group by Stage',
    groupByJob: 'Group by Job',
    kanbanView: 'Kanban View',
    listView: 'List View',
    addCandidate: 'Add Candidate',
    searchLinkedIn: 'Search LinkedIn',
    bulkActions: 'Bulk Actions',
    moveToStage: 'Move to Stage',
    bulkMoveDescription: 'Move selected candidates to another stage',
    addTags: 'Add Tags',
    bulkTagsDescription: 'Add tags to selected candidates',
    sendEmail: 'Send Email',
    bulkEmailDescription: 'Send email to selected candidates',
    exportCandidates: 'Export Candidates',
    bulkExportDescription: 'Export selected candidates to CSV',
    deleteCandidates: 'Delete Candidates',
    bulkDeleteDescription: 'Delete selected candidates permanently',
    noCandidateForJob: 'No candidates for this job',
    addCandidateForJob: 'Add Candidate',
    selectJob: 'Select a job position',
    jobRequisition: 'Job Position',
    unknownJob: 'Unknown Job',
    previousPage: 'Previous Page',
    nextPage: 'Next Page',
    noJobsFound: 'No Jobs Found',
    createJobFirst: 'Create a job requisition first',
    createJobRequisition: 'Create Job Requisition',
    cancel: 'Cancel',
    noCandidateForJob: 'No candidates for this job',
    addCandidateForJob: 'Add Candidate',
    selectJob: 'Select Job',
    jobRequisition: 'Job Requisition',
    unknownJob: 'Unknown Job',
    previousPage: 'Previous Page',
    nextPage: 'Next Page',
    noJobsFound: 'No Jobs Found',
    createJobFirst: 'Create a job requisition first',
    createJobRequisition: 'Create Job Requisition',
    selectJobForImport: 'Select job for importing candidates',
    viewProfile: 'View Profile',
    selectCandidate: 'Select Candidate',
    about: 'About',
    experience: 'Experience',
    education: 'Education',
    skills: 'Skills',
    aiAnalysis: 'AI Analysis',
    overallFitScore: 'Overall Job Fit',
    scoreBreakdown: 'Score Breakdown',
    technicalSkills: 'Technical Skills',
    cultureFit: 'Culture Fit',
    strengths: 'Strengths',
    gaps: 'Areas for Development',
    aiAnalysisInfo: 'AI-powered analysis based on job requirements and candidate profile',
    selectJobForAnalysis: 'Please select a job requisition to view AI analysis',
    generatingAnalysis: 'Generating AI Analysis',
    aiProcessingInfo: 'Our AI is analyzing this profile against the selected job requirements',
    jobSelectionRequired: 'Select a job requisition from the dropdown to enable analysis',
    selectToAdd: 'Select Candidate First',
    addToRecruitment: 'Add to Recruitment Process',
    close: 'Close',
    linkedInTalentSearch: 'LinkedIn Talent Search',
    searchingForJob: 'Searching for candidates for: {{job}}',
    searchForCandidates: 'Search for candidates on LinkedIn',
    searchLinkedInPlaceholder: 'Search by name, title, or keyword',
    analyzeResults: 'Analyze Results',
    analysis: 'Analysis',
    jobRequirementAnalysis: 'Job Requirement Analysis',
    skillRequirements: 'Skill Requirements',
    required: 'Required',
    candidateAvailability: 'Candidate Availability',
    activeCandidates: 'Active Candidates',
    openToWork: 'Open to Work',
    averageResponseRate: 'Average Response Rate',
    estimatedTimeToHire: 'Estimated Time to Hire',
    weeks: 'weeks',
    topCandidateMatches: 'Top Candidate Matches',
    viewProfile: 'View Profile',
    importCandidates: 'Import Candidates',
    noSearchResults: 'No search results found',
    tryDifferentSearch: 'Try a different search term',
    analyzingProfiles: 'Analyzing candidate profiles...',
    addCandidateForJob: 'Add Candidate',
    noCandidateForJob: 'No candidates for this job',
    allJobs: 'All Jobs',
    previousPage: 'Previous Page',
    nextPage: 'Next Page',
    pageInfo: 'Page {{current}} of {{total}}',
    candidateTimeline: 'Candidate Timeline',
    addNote: 'Add Note',
    scheduleInterview: 'Schedule Interview',
    finalEvaluation: 'Final Evaluation',
    questionAsked: 'Question Asked',
    interviewHistory: 'Interview History',
    overview: 'Overview',
    education: 'Education',
    experience: 'Experience',
    skills: 'Skills',
    certifications: 'Certifications & Courses',
    documents: 'Documents & Links',
    currentLocation: 'Current Location',
    preferredWorkMode: 'Preferred Work Mode',
    remote: 'Remote',
    onsite: 'On-site',
    hybrid: 'Hybrid',
    degree: 'Degree',
    major: 'Major',
    graduationYear: 'Graduation Year',
    gpa: 'GPA',
    institution: 'Institution',
    company: 'Company',
    jobTitle: 'Job Title',
    duration: 'Duration',
    achievements: 'Key Achievements',
    present: 'Present',
    technicalSkills: 'Technical Skills',
    softSkills: 'Soft Skills',
    languages: 'Languages',
    proficiency: 'Proficiency',
    basic: 'Basic',
    intermediate: 'Intermediate',
    fluent: 'Fluent',
    native: 'Native',
    certificationName: 'Certification',
    provider: 'Provider',
    issueDate: 'Issue Date',
    expiryDate: 'Expiry Date',
    credentialId: 'Credential ID',
    viewDocument: 'View Document',
    downloadDocument: 'Download Document',
    uploadedOn: 'Uploaded on',
    downloadCandidateReport: 'Download Candidate Report',
    requestAdditionalInfo: 'Request Additional Info',
    noEducationRecords: 'No education records available',
    noExperienceRecords: 'No work experience records available',
    noSkillsRecords: 'No skills information available',
    noCertificationRecords: 'No certifications or courses available',
    noDocumentsAvailable: 'No documents available',
    similarCandidates: 'Similar Candidates',
    basedOn: 'Based on',
    findingSimilarCandidates: 'Finding Similar Candidates',
    analyzingProfiles: 'Analyzing profiles based on skills and experience...',
    candidatesFound: 'candidates found',
    sortBy: 'Sort by',
    bestMatch: 'Best Match',
    highestAiScore: 'Highest AI Score',
    alphabetical: 'Alphabetical',
    recentlyAdded: 'Recently Added',
    match: 'Match',
    yearExp: 'year exp',
    yearsExp: 'years exp',
    viewFullProfile: 'View Full Profile',
    compareWithCurrent: 'Compare With Current',
    scheduleInterviewFor: 'Schedule Interview for',
    interviewDate: 'Interview Date',
    interviewTime: 'Interview Time',
    interviewType: 'Interview Type',
    videoInterview: 'Video Interview',
    phoneInterview: 'Phone Interview',
    inPersonInterview: 'In-Person Interview',
    interviewers: 'Interviewers',
    sendCalendarInvite: 'Send calendar invite to candidate',
    interviewNotes: 'Notes for interviewers',
    rejectCandidate: 'Reject Candidate',
    rejectionReason: 'Rejection Reason',
    selectRejectionReason: 'Select reason for rejection',
    customRejectionReason: 'Custom Rejection Reason',
    enterCustomReason: 'Enter your custom rejection reason',
    sendRejectionEmail: 'Send rejection email to candidate',
    emailPreview: 'Email Preview',
    dear: 'Dear',
    rejectionEmailText: 'Thank you for your interest in our company. After careful consideration, we regret to inform you that we will not be proceeding with your application at this time.',
    rejectionEmailClosing: 'We appreciate your time and interest in our organization and wish you the best in your future endeavors.',
    regards: 'Best regards',
    wiseRecruitmentTeam: 'The Wise Recruitment Team',
    confirmRejection: 'Confirm Rejection',
    notQualified: 'Not qualified for the role',
    lackExperience: 'Insufficient experience',
    skillsMismatch: 'Skills mismatch with requirements',
    salaryExpectations: 'Salary expectations too high',
    locationIssue: 'Location/relocation issues',
    betterCandidates: 'Other candidates better fit the role',
    jobCancelled: 'Position put on hold/cancelled',
    other: 'Other reason',
    addNoteForCandidate: 'Add Note for',
    enterNoteAboutCandidate: 'Enter your observations, feedback, or notes about this candidate',
    privateNote: 'Private note (only visible to you)',
    privateNoteDescription: 'This note will only be visible to you and not to other team members',
    saveNote: 'Save Note',
    compareCandidates: 'Compare Candidates',
    similarityScore: 'Similarity Score',
    overallMatch: 'Overall Match',
    skillsMatch: 'Skills Match',
    experienceMatch: 'Experience Match',
    matchFound: 'Match found with current candidate',
    more: 'more',
    notSpecified: 'Not specified',
    noJobTitle: 'No job title specified',
    moveToStage: 'Move to Stage',
    interview: 'Interview',
    reject: 'Reject',
  },
  ar: {
    welcome: 'مرحبًا بك في وايز',
    recruitment: 'التوظيف',
    analytics: 'التحليلات',
    jobRequisition: 'طلب الوظيفة',
    candidate: 'المرشح',
    interview: 'المقابلة',
    offer: 'العرض',
    onboarding: 'التأهيل',
    careersPortalSetup: 'إعداد بوابة الوظائف',
    contentComingSoon: 'المحتوى قادم قريبًا',
    groupByStage: 'تجميع حسب المرحلة',
    groupByJob: 'تجميع حسب الوظيفة',
    kanbanView: 'عرض كانبان',
    listView: 'عرض القائمة',
    filters: 'تصفية',
    source: 'المصدر',
    aiScore: 'درجة الذكاء الاصطناعي',
    nationality: 'الجنسية',
    stage: 'المرحلة',
    new: 'جديد',
    shortlisted: 'القائمة المختصرة',
    interviewed: 'تمت المقابلة',
    offered: 'تم تقديم العرض',
    hired: 'تم التعيين',
    rejected: 'مرفوض',
    addCandidate: 'إضافة مرشح',
    searchLinkedIn: 'البحث في لينكد إن',
    bulkActions: 'إجراءات جماعية',
    moveToStage: 'نقل إلى مرحلة',
    bulkMoveDescription: 'نقل المرشحين المحددين إلى مرحلة مختلفة',
    addTags: 'إضافة علامات',
    bulkTagsDescription: 'إضافة علامات إلى المرشحين المحددين',
    sendEmail: 'إرسال بريد إلكتروني',
    bulkEmailDescription: 'إرسال بريد إلكتروني إلى المرشحين المحددين',
    exportCandidates: 'تصدير',
    bulkExportDescription: 'تصدير المرشحين المحددين إلى CSV/PDF',
    deleteCandidates: 'حذف',
    bulkDeleteDescription: 'إزالة المرشحين المحددين من النظام',
    cancel: 'إلغاء',
    noCandidateForJob: 'لا يوجد مرشحين لهذا الوظيفة',
    addCandidateForJob: 'إضافة مرشح',
    selectJob: 'اختر الوظيفة',
    jobRequisition: 'المنصب الوظيفي',
    unknownJob: 'وظيفة غير معروفة',
    previousPage: 'الصفحة السابقة',
    nextPage: 'الصفحة التالية',
    noJobsFound: 'لا يوجد الوظائف',
    createJobFirst: 'إنشاء طلب الوظيفة أولاً',
    createJobRequisition: 'إنشاء طلب الوظيفة',
    matchScore: 'درجة التطابق',
    stage1: 'المرحلة 1',
    stage2: 'المرحلة 2',
    stage3: 'المرحلة 3',
    pageInfo: 'الصفحة {current} من {total}',
    linkedInSearchInfo: 'معلومات البحث في لينكد إن',
    searchForCandidates: 'البحث عن المرشحين',
    apply: 'تطبيق',
    uploadCv: 'تحميل السيرة الذاتية',
    emailTemplateInfo: 'معلومات قالب البريد الإلكتروني',
    findOnLinkedIn: 'البحث في لينكد إن',
    findSimilarCandidates: 'البحث عن مرشحين مشابهين',
    groupByStage: 'تجميع حسب المرحلة',
    groupByJob: 'تجميع حسب الوظيفة',
    kanbanView: 'عرض كانبان',
    listView: 'عرض القائمة',
    addCandidate: 'إضافة مرشح',
    searchLinkedIn: 'البحث في لينكد إن',
    bulkActions: 'إجراءات جماعية',
    moveToStage: 'نقل إلى مرحلة',
    bulkMoveDescription: 'نقل المرشحين المحددين إلى مرحلة مختلفة',
    addTags: 'إضافة علامات',
    bulkTagsDescription: 'إضافة علامات إلى المرشحين المحددين',
    sendEmail: 'إرسال بريد إلكتروني',
    bulkEmailDescription: 'إرسال بريد إلكتروني إلى المرشحين المحددين',
    exportCandidates: 'تصدير',
    bulkExportDescription: 'تصدير المرشحين المحددين إلى CSV/PDF',
    deleteCandidates: 'حذف',
    bulkDeleteDescription: 'إزالة المرشحين المحددين من النظام',
    cancel: 'إلغاء',
    noCandidateForJob: 'لا يوجد مرشحين لهذا الوظيفة',
    addCandidateForJob: 'إضافة مرشح',
    selectJob: 'اختيار الوظيفة',
    jobRequisition: 'طلب الوظيفة',
    unknownJob: 'وظيفة غير معروفة',
    previousPage: 'الصفحة السابقة',
    nextPage: 'الصفحة التالية',
    noJobsFound: 'لا يوجد الوظائف',
    createJobFirst: 'إنشاء طلب الوظيفة أولاً',
    createJobRequisition: 'إنشاء طلب الوظيفة',
    selectJobForImport: 'اختر الوظيفة لاستيراد المرشحين',
    viewProfile: 'عرض الملف الشخصي',
    selectCandidate: 'اختيار المرشح',
    about: 'نبذة',
    experience: 'الخبرة',
    education: 'التعليم',
    skills: 'المهارات',
    aiAnalysis: 'تحليل الذكاء الاصطناعي',
    overallFitScore: 'ملاءمة الوظيفة الإجمالية',
    scoreBreakdown: 'تفاصيل الدرجات',
    technicalSkills: 'المهارات التقنية',
    cultureFit: 'التوافق الثقافي',
    strengths: 'نقاط القوة',
    gaps: 'مجالات للتطوير',
    aiAnalysisInfo: 'تحليل مدعوم بالذكاء الاصطناعي بناءً على متطلبات الوظيفة وملف المرشح',
    selectJobForAnalysis: 'الرجاء تحديد طلب وظيفة لعرض تحليل الذكاء الاصطناعي',
    generatingAnalysis: 'جاري إنشاء تحليل الذكاء الاصطناعي',
    aiProcessingInfo: 'يقوم الذكاء الاصطناعي لدينا بتحليل هذا الملف الشخصي مقارنة بمتطلبات الوظيفة المحددة',
    jobSelectionRequired: 'حدد طلب وظيفة من القائمة المنسدلة لتمكين التحليل',
    selectToAdd: 'حدد المرشح أولاً',
    addToRecruitment: 'إضافة إلى عملية التوظيف',
    close: 'إغلاق',
    linkedInTalentSearch: 'بحث المواهب على لينكد إن',
    searchingForJob: 'البحث عن مرشحين لـ: {{job}}',
    searchForCandidates: 'البحث عن المرشحين على لينكد إن',
    searchLinkedInPlaceholder: 'البحث بالاسم، أو المسمى الوظيفي، أو الكلمة الرئيسية',
    analyzeResults: 'تحليل النتائج',
    analysis: 'التحليل',
    jobRequirementAnalysis: 'تحليل متطلبات الوظيفة',
    skillRequirements: 'المهارات المطلوبة',
    required: 'مطلوب',
    candidateAvailability: 'توفر المرشحين',
    activeCandidates: 'المرشحون النشطون',
    openToWork: 'منفتحون للعمل',
    averageResponseRate: 'معدل الاستجابة',
    estimatedTimeToHire: 'الوقت المقدر للتوظيف',
    weeks: 'أسابيع',
    topCandidateMatches: 'أفضل المرشحين المطابقين',
    viewProfile: 'عرض الملف الشخصي',
    importCandidates: 'استيراد المرشحين',
    noSearchResults: 'لم يتم العثور على نتائج',
    tryDifferentSearch: 'جرب مصطلح بحث مختلف',
    analyzingProfiles: 'تحليل ملفات المرشحين...',
    addCandidateForJob: 'إضافة مرشح',
    noCandidateForJob: 'لا يوجد مرشحين لهذه الوظيفة',
    allJobs: 'جميع الوظائف',
    previousPage: 'الصفحة السابقة',
    nextPage: 'الصفحة التالية',
    pageInfo: 'الصفحة {{current}} من {{total}}',
    candidateTimeline: 'الجدول الزمني للمرشح',
    addNote: 'إضافة ملاحظة',
    scheduleInterview: 'جدولة مقابلة',
    finalEvaluation: 'التقييم النهائي',
    questionAsked: 'السؤال المطروح',
    interviewHistory: 'سجل المقابلات',
    overview: 'نظرة عامة',
    education: 'التعليم',
    experience: 'الخبرة المهنية',
    skills: 'المهارات',
    certifications: 'الشهادات والدورات',
    documents: 'المستندات والروابط',
    currentLocation: 'الموقع الحالي',
    preferredWorkMode: 'نمط العمل المفضل',
    remote: 'عن بعد',
    onsite: 'في الموقع',
    hybrid: 'هجين',
    degree: 'الدرجة العلمية',
    major: 'التخصص',
    graduationYear: 'سنة التخرج',
    gpa: 'المعدل التراكمي',
    institution: 'المؤسسة التعليمية',
    company: 'الشركة',
    jobTitle: 'المسمى الوظيفي',
    duration: 'المدة',
    achievements: 'الإنجازات الرئيسية',
    present: 'حتى الآن',
    technicalSkills: 'المهارات التقنية',
    softSkills: 'المهارات الشخصية',
    languages: 'اللغات',
    proficiency: 'مستوى الإتقان',
    basic: 'أساسي',
    intermediate: 'متوسط',
    fluent: 'طليق',
    native: 'لغة أم',
    certificationName: 'الشهادة',
    provider: 'الجهة المانحة',
    issueDate: 'تاريخ الإصدار',
    expiryDate: 'تاريخ الانتهاء',
    credentialId: 'رقم الشهادة',
    viewDocument: 'عرض المستند',
    downloadDocument: 'تنزيل المستند',
    uploadedOn: 'تم التحميل في',
    downloadCandidateReport: 'تنزيل تقرير المرشح',
    requestAdditionalInfo: 'طلب معلومات إضافية',
    noEducationRecords: 'لا توجد سجلات تعليمية متاحة',
    noExperienceRecords: 'لا توجد سجلات خبرة عمل متاحة',
    noSkillsRecords: 'لا توجد معلومات عن المهارات متاحة',
    noCertificationRecords: 'لا توجد شهادات أو دورات متاحة',
    noDocumentsAvailable: 'لا توجد مستندات متاحة',
    similarCandidates: 'مرشحون مماثلين',
    basedOn: 'بناءً على',
    findingSimilarCandidates: 'البحث عن مرشحين مماثلين',
    analyzingProfiles: 'تحليل الملفات الشخصية بناءً على المهارات والخبرة...',
    candidatesFound: 'مرشحين تم العثور عليهم',
    sortBy: 'ترتيب حسب',
    bestMatch: 'أفضل تطابق',
    highestAiScore: 'أعلى درجة ذكاء اصطناعي',
    alphabetical: 'أبجدي',
    recentlyAdded: 'أضيف حديثًا',
    match: 'تطابق',
    yearExp: 'سنة خبرة',
    yearsExp: 'سنوات خبرة',
    viewFullProfile: 'عرض الملف الكامل',
    compareWithCurrent: 'مقارنة مع المرشح الحالي',
    scheduleInterviewFor: 'جدولة مقابلة لـ',
    interviewDate: 'تاريخ المقابلة',
    interviewTime: 'وقت المقابلة',
    interviewType: 'نوع المقابلة',
    videoInterview: 'مقابلة فيديو',
    phoneInterview: 'مقابلة هاتفية',
    inPersonInterview: 'مقابلة شخصية',
    interviewers: 'المقابلون',
    sendCalendarInvite: 'إرسال دعوة تقويم للمرشح',
    interviewNotes: 'ملاحظات للمقابلين',
    rejectCandidate: 'رفض المرشح',
    rejectionReason: 'سبب الرفض',
    selectRejectionReason: 'اختر سبب الرفض',
    customRejectionReason: 'سبب رفض مخصص',
    enterCustomReason: 'أدخل سبب الرفض المخصص',
    sendRejectionEmail: 'إرسال بريد إلكتروني بالرفض للمرشح',
    emailPreview: 'معاينة البريد الإلكتروني',
    dear: 'عزيزي',
    rejectionEmailText: 'نشكرك على اهتمامك بشركتنا. بعد دراسة متأنية، نأسف لإبلاغك بأننا لن نواصل طلبك في الوقت الحالي.',
    rejectionEmailClosing: 'نقدر وقتك واهتمامك بمؤسستنا ونتمنى لك التوفيق في مساعيك المستقبلية.',
    regards: 'مع أطيب التحيات',
    wiseRecruitmentTeam: 'فريق التوظيف في وايز',
    confirmRejection: 'تأكيد الرفض',
    notQualified: 'غير مؤهل للدور',
    lackExperience: 'خبرة غير كافية',
    skillsMismatch: 'عدم تطابق المهارات مع المتطلبات',
    salaryExpectations: 'توقعات الراتب مرتفعة جدا',
    locationIssue: 'مشاكل في الموقع/الانتقال',
    betterCandidates: 'مرشحون آخرون أكثر ملاءمة للدور',
    jobCancelled: 'تم تعليق/إلغاء المنصب',
    other: 'سبب آخر',
    addNoteForCandidate: 'إضافة ملاحظة لـ',
    enterNoteAboutCandidate: 'أدخل ملاحظاتك وتقييمك لهذا المرشح',
    privateNote: 'ملاحظة خاصة (مرئية لك فقط)',
    privateNoteDescription: 'هذه الملاحظة ستكون مرئية لك فقط وليس لأعضاء الفريق الآخرين',
    saveNote: 'حفظ الملاحظة',
    compareCandidates: 'مقارنة المرشحين',
    similarityScore: 'درجة التشابه',
    overallMatch: 'التطابق الكلي',
    skillsMatch: 'تطابق المهارات',
    experienceMatch: 'تطابق الخبرة',
    matchFound: 'تم العثور على تطابق مع المرشح الحالي',
    more: 'المزيد',
    notSpecified: 'غير محدد',
    noJobTitle: 'المسمى الوظيفي غير محدد',
    moveToStage: 'نقل إلى مرحلة',
    interview: 'مقابلة',
    reject: 'رفض',
  },
};

// Add a formatter function for string interpolation
const formatMessage = (template: string, values: Record<string, any>) => {
  return template.replace(/{(\w+)}/g, (match, key) => {
    return values[key] !== undefined ? values[key] : match;
  });
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const { language, setLanguage } = useAppContext();
  const t = (key: string, values?: Record<string, any>): string => {
    const template = translations[language][key as keyof typeof translations.en] || key;
    return values ? formatMessage(template, values) : template;
  };
  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
};