/**
 * Auto-generated Three.js component list
 * Generated on: 2025-06-14T05:15:44.362Z
 *
 * This file is automatically generated by scripts/test-3d.cjs
 * Do not edit manually - run the script to regenerate
 */
export declare const threeJsComponents: any;
export default threeJsComponents;
export declare const metadata: {
    generatedAt: string;
    totalComponents: number;
    source: string;
};
