import React, { createContext, useContext, useState, useEffect } from 'react';
import { useAppContext } from '../../../../../context/app-context';

type Language = 'en' | 'ar';
type Direction = 'ltr' | 'rtl';

interface LanguageContextType {
  language: Language;
  direction: Direction;
  changeLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    welcomeToWise: 'Welcome to Wise',
    recruitment: 'Recruitment',
    analytics: 'Analytics',
    jobRequisition: 'Job Requisition',
    candidate: 'Candidate',
    interview: 'Interview',
    offer: 'Offer',
    onboarding: 'Onboarding',
    careersPortalSetup: 'Careers Portal Setup',
    contentComingSoon: 'Content coming soon',
    collapse: 'Collapse',
    // Onboarding module translations
    onboardingManagement: 'Onboarding Management',
    startOnboarding: 'Start Onboarding',
    dashboard: 'Dashboard',
    activeOnboarding: 'Active Onboarding',
    completedOnboarding: 'Completed Onboarding',
    templates: 'Templates',
    settings: 'Settings',
    onboardingSettings: 'Onboarding Settings',
    settingsDescription: 'Configure onboarding defaults, notification preferences, and compliance settings.',
    totalOnboardings: 'Total Onboardings',
    thisMonth: 'This Month',
    ytd: 'YTD',
    completionRate: 'Completion Rate',
    averagePerEmployee: 'Average Per Employee',
    targetRate: 'Target Rate',
    delayedTasks: 'Delayed Tasks',
    requiresAttention: 'Requires Attention',
    critical: 'Critical',
    activeTemplates: 'Active Templates',
    mostUsed: 'Most Used',
    department: 'Department',
    onboardingProgress: 'Onboarding Progress',
    aiInsights: 'AI Insights',
    aiInsight1: 'IT department onboarding has 92% completion rate, above company average.',
    aiInsight2: 'Document submission tasks have the highest delay rate (23%).',
    aiInsight3: 'Consider adding "System Access" task to the Finance template based on peer company data.',
    taskCompletionByType: 'Task Completion by Type',
    adminTasks: 'Admin Tasks',
    complianceTasks: 'Compliance Tasks',
    trainingTasks: 'Training Tasks',
    techSetupTasks: 'Tech Setup Tasks',
    orientationTasks: 'Orientation Tasks',
    upcomingDeadlines: 'Upcoming Deadlines',
    searchEmployeeDepartment: 'Search by employee or department',
    newTemplate: 'New Template',
    filter: 'Filter',
    allDepartments: 'All Departments',
    finance: 'Finance',
    sales: 'Sales',
    employee: 'Employee',
    templateName: 'Template Name',
    position: 'Position',
    tasksCount: 'Tasks Count',
    owner: 'Owner',
    startDate: 'Start Date',
    progress: 'Progress',
    actions: 'Actions',
    noRecordsFound: 'No records found',
    tasks: 'Tasks',
    view: 'View',
    edit: 'Edit',
    duplicate: 'Duplicate',
    delete: 'Delete',
    sendReminder: 'Send Reminder',
    markComplete: 'Mark Complete',
    reassign: 'Reassign',
    archive: 'Archive',
    completed: 'Completed',
    inProgress: 'In Progress',
    ongoing: 'Ongoing',
    justStarted: 'Just Started',
    employeeProfile: 'Employee Profile',
    documents: 'Documents',
    owner: 'Owner',
    tasks: 'Tasks',
    review: 'Review',
    employeeProfileStep: 'Employee Profile',
    employeeProfileDesc: 'Fill in or confirm the employee information details',
    fullName: 'Full Name',
    enterFullName: 'Enter full name',
    email: 'Email',
    enterEmail: 'Enter email',
    phone: 'Phone',
    enterPhone: 'Enter phone number',
    nationalId: 'National ID/Iqama',
    enterNationalId: 'Enter ID number',
    saudiIdOrIqama: 'Saudi ID or Iqama for non-Saudis',
    gosiId: 'GOSI ID',
    enterGosiId: 'Enter GOSI number',
    enterPosition: 'Enter position',
    selectDepartment: 'Select department',
    selectManager: 'Select manager',
    selectStartDate: 'Select start date',
    joiningLocation: 'Joining Location',
    enterLocation: 'Enter location',
    contractType: 'Contract Type',
    selectContractType: 'Select contract type',
    permanent: 'Permanent',
    contract: 'Contract',
    probation: 'Probation',
    employeeType: 'Employee Type',
    selectEmployeeType: 'Select employee type',
    saudiNational: 'Saudi National',
    expat: 'Expatriate',
    aiProfileCompletionTip: 'AI has auto-completed some fields based on the candidate record. Please verify the information.',
    requiredDocumentsStep: 'Required Documents',
    requiredDocumentsDesc: 'Upload the necessary documents for employee onboarding',
    document_passport: 'Passport Copy',
    document_nationalId: 'National ID/Iqama',
    document_certificates: 'Educational Certificates',
    document_bankInfo: 'Bank Account Information',
    document_signedOffer: 'Signed Offer Letter',
    document_passport_desc: 'Clear copy of passport information page',
    document_nationalId_desc: 'Front and back of National ID or Iqama',
    document_certificates_desc: 'Academic and professional certifications',
    document_bankInfo_desc: 'Bank account details for salary transfer',
    document_signedOffer_desc: 'Completed and signed offer acceptance',
    addCustomDocument: 'Add Custom Document',
    addFullCycle: 'Add Full Cycle',
    assignOnboardingOwnerStep: 'Assign Onboarding Owner',
    assignOwnerDesc: 'Select a team member to oversee this onboarding process',
    assignOnboardingOwner: 'Assign Onboarding Owner',
    selectOwner: 'Select owner',
    ownerResponsibilities: 'Owner Responsibilities',
    ownerResponsibility1: 'Guide the employee through the onboarding process',
    ownerResponsibility2: 'Ensure timely completion of all required tasks',
    ownerResponsibility3: 'Resolve issues that may arise during onboarding',
    ownerResponsibility4: 'Provide regular status updates to HR and management',
    aiOwnerSuggestion: 'Based on department and role, AI suggests assigning HR Specialist Sara Al-Qahtani as the onboarding owner.',
    setupOnboardingTasksStep: 'Setup Onboarding Tasks',
    setupTasksDesc: 'Create tasks that need to be completed during the onboarding process',
    totalTasks: 'Total Tasks',
    taskTypeDistribution: 'Tasks distributed by type and priority',
    useTemplate: 'Use Template',
    addTask: 'Add Task',
    noDueDate: 'No due date',
    assignedTo: 'Assigned to',
    marketing: 'Marketing',
    reviewAndConfirmStep: 'Review & Confirm',
    reviewAndConfirmDesc: 'Review all onboarding details before finalizing',
    employeeDetails: 'Employee Details',
    name: 'Name',
    allUploaded: 'All Uploaded',
    uploaded: 'Uploaded',
    notAssigned: 'Not Assigned',
    tasksSummary: 'Tasks Summary',
    addMore: 'Add More',
    previousStep: 'Previous Step',
    nextStep: 'Next Step',
    createOnboarding: 'Create Onboarding',
    saveAsDraft: 'Save as Draft',
    cancel: 'Cancel',
    aiSuggestion: 'AI Suggestion',
    aiOnboardingSuggestionText: 'Based on the employee\'s profile (IT department, expat status), consider adding tasks for work permit validation and IT systems access training.',
    additionalNotes: 'Additional Notes',
    enterAdditionalNotes: 'Enter any additional notes for this onboarding process',
    onboardingWizard: 'Onboarding Wizard',
    onboardingWizardDesc: 'Create a structured onboarding journey for your new employee',
    onboardingProgress: 'Onboarding Progress',
    step: 'Step',
    of: 'of',
    createNewTask: 'Create New Task',
    taskTitle: 'Task Title',
    enterTaskTitle: 'Enter task title',
    taskType: 'Task Type',
    selectTaskType: 'Select task type',
    admin: 'Admin',
    compliance: 'Compliance',
    training: 'Training',
    techSetup: 'Tech Setup',
    orientation: 'Orientation',
    dueDate: 'Due Date',
    selectDueDate: 'Select due date',
    taskDescription: 'Task Description',
    enterTaskDescription: 'Enter task description',
    attachFile: 'Attach File',
    addLink: 'Add Link',
    completeGOSIRegistration: 'Complete GOSI Registration',
    setupEmailAccount: 'Setup Email Account',
    completeOrientationTraining: 'Complete Orientation Training',
    signEmploymentContract: 'Sign Employment Contract',
    submitBankDetails: 'Submit Bank Details',
    overdue: 'Overdue',
    onTrack: 'On Track',
    required: 'Required',
    upload: 'Upload',
    preview: 'Preview',
    change: 'Change',
    onboardingListTable: 'Onboarding List Table',
    month: 'Month',
    totalCompletion: 'Total Completion',
    
    // New translations for candidate auto-loading feature
    candidateInfoAutoLoaded: 'Candidate information has been pre-loaded. Please verify and update as needed.',
    loadingCandidateInfo: 'Loading candidate information...',
    candidateInfoEditableNote: 'All pre-loaded candidate information can be updated if needed before proceeding.',
    
    // Add new translations for candidate selection
    selectCandidate: 'Select Candidate',
    selectCandidateToOnboard: 'Select a candidate to onboard',
    candidateSelected: 'Candidate selected',
    
    // Add new translations for task editing
    editTask: 'Edit Task',
    saveChanges: 'Save Changes',
    assignTo: 'Assign To',
    selectAssignee: 'Select Assignee',
    taskPriority: 'Task Priority',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    markAsRequired: 'Mark as Required',
    
    // Add template selection translations
    selectOnboardingTemplate: 'Select Onboarding Template',
    selectTemplateInstructions: 'Choose a template to quickly add pre-defined tasks for this onboarding process.',
    fullCycleTemplateDescription: 'Recommended: Includes administrative, compliance, training, and technical setup tasks for a complete onboarding experience.',
    applyTemplate: 'Apply Template',
    
    // Add new document-related translations
    documentName: 'Document Name',
    enterDocumentName: 'Enter document name',
    documentDescription: 'Document Description',
    enterDocumentDescription: 'Enter document description',
    addDocument: 'Add Document',
    
    // Add new translations to the English translations object
    createNewTemplate: 'Create New Template',
    enterTemplateName: 'Enter template name',
    assignOwner: 'Assign Owner',
    selectTaskTypes: 'Select Task Types',
    templateDescription: 'Template Description',
    enterTemplateDescription: 'Enter template description',
    requiredDocuments: 'Required Documents',
    saveAndContinue: 'Save & Continue',
    
    // Add new settings-related translations to the English translations object
    saveSettings: 'Save Settings',
    generalSettings: 'General Settings',
    notificationSettings: 'Notification Settings',
    complianceSettings: 'Compliance Settings',
    taskSettings: 'Task Settings',
    integrations: 'Integrations',
    accessControl: 'Access Control',
    defaultSettings: 'Default Settings',
    defaultOnboardingDuration: 'Default Onboarding Duration',
    days: 'days',
    durationDescription: 'Default duration for onboarding process completion',
    defaultTemplate: 'Default Template',
    selectDefaultTemplate: 'Select default template',
    defaultOwner: 'Default Owner',
    selectDefaultOwner: 'Select default owner',
    autoAssignBasedOnDepartment: 'Auto-assign based on department',
    defaultOnboardingLanguage: 'Default Onboarding Language',
    selectLanguage: 'Select language',
    automationSettings: 'Automation Settings',
    enableAutomation: 'Enable Automation',
    automationDescription: 'Automatically assign tasks based on employee role and department',
    sendWelcomeEmail: 'Send Welcome Email',
    welcomeEmailDescription: 'Automatically send welcome email when onboarding starts',
    enableAiSuggestions: 'Enable AI Suggestions',
    aiSuggestionsDescription: 'Use AI to suggest optimal onboarding tasks and workflows',
    new: 'New',
    emailNotifications: 'Email Notifications',
    defaultFrequency: 'Default Frequency',
    immediately: 'Immediately',
    dailyDigest: 'Daily Digest',
    weeklyDigest: 'Weekly Digest',
    onboardingStartNotification: 'Onboarding Start',
    onboardingStartDescription: 'When a new onboarding process begins',
    taskAssignedNotification: 'Task Assigned',
    taskAssignedDescription: 'When a task is assigned to a user',
    taskDueNotification: 'Task Due Soon',
    taskDueDescription: 'When a task is approaching its due date',
    documentUploadedNotification: 'Document Uploaded',
    documentUploadedDescription: 'When a document is uploaded to the system',
    onboardingCompleteNotification: 'Onboarding Complete',
    onboardingCompleteDescription: 'When an onboarding process is completed',
    taskOverdueNotification: 'Task Overdue',
    taskOverdueDescription: 'When a task becomes overdue',
    managerApprovalNotification: 'Manager Approval',
    managerApprovalDescription: 'When manager approval is needed',
    systemNotifications: 'System Notifications',
    enableInAppNotifications: 'Enable In-App Notifications',
    inAppNotificationsDescription: 'Show notifications within the application',
    enablePushNotifications: 'Enable Push Notifications',
    pushNotificationsDescription: 'Send notifications to desktop or mobile device',
    enableSlackNotifications: 'Enable Slack Notifications',
    slackNotificationsDescription: 'Send notifications to connected Slack channels',
    enableSmsNotifications: 'Enable SMS Notifications',
    smsNotificationsDescription: 'Send text message notifications for critical events',
    reminderSettings: 'Reminder Settings',
    sendTaskReminders: 'Send Task Reminders',
    taskRemindersSettingDescription: 'When to send reminders for upcoming tasks',
    oneDayBefore: '1 day before',
    threeDaysBefore: '3 days before',
    oneWeekBefore: '1 week before',
    custom: 'Custom',
    sendEscalationNotifications: 'Send Escalation Notifications',
    escalationNotificationsDescription: 'When to escalate overdue tasks to managers',
    oneDay: '1 day after due date',
    twoDays: '2 days after due date',
    threeDays: '3 days after due date',
    oneWeek: '1 week after due date',
    never: 'Never',
    documentRequirements: 'Document Requirements',
    documentType: 'Document Type',
    required: 'Required',
    defaultForAll: 'Default for All',
    appliesTo: 'Applies To',
    actions: 'Actions',
    allEmployees: 'All Employees',
    expatsOnly: 'Expats Only',
    documentWorkPermit: 'Work Permit',
    employmentContract: 'Employment Contract',
    medicalInsurance: 'Medical Insurance Certificate',
    addDocumentType: 'Add Document Type',
    documentRequirementsNote: 'Documents marked as required must be uploaded before onboarding can be completed. Default documents will be automatically included in all new onboarding processes.',
    complianceRules: 'Compliance Rules',
    enforceDocumentExpiration: 'Enforce Document Expiration',
    documentExpirationDescription: 'Track expiration dates for documents and send reminders',
    enforceBackgroundChecks: 'Enforce Background Checks',
    backgroundChecksDescription: 'Require background verification before completing onboarding',
    enforceSignatureVerification: 'Enforce Signature Verification',
    signatureVerificationDescription: 'Require digital signatures for key documents',
    requireManagerApproval: 'Require Manager Approval',
    managerApprovalDescription: 'Require manager approval for onboarding completion',
    localRegulations: 'Local Regulations',
    saudiComplianceInfo: 'Saudi Arabia Compliance Requirements',
    saudiComplianceDescription: 'Includes GOSI registration, Saudization requirements, and Ministry of Labor compliance',
    enforceGOSIRegistration: 'Enforce GOSI Registration',
    gosiComplianceTooltip: 'General Organization for Social Insurance registration required for all employees',
    enforceSaudization: 'Enforce Saudization Rules',
    saudizationTooltip: 'Ensures compliance with Saudi nationalization employment requirements',
    taskTypes: 'Task Types',
    addTaskType: 'Add Task Type',
    taskType: 'Task Type',
    color: 'Color',
    description: 'Description',
    systemDefault: 'System Default',
    save: 'Save',
    adminTasksDescription: 'Administrative tasks like paperwork and system setup',
    complianceTasksDescription: 'Tasks related to legal and regulatory compliance',
    trainingTasksDescription: 'Employee training and development activities',
    techSetupTasksDescription: 'Technical systems and hardware setup tasks',
    orientationTasksDescription: 'Company and team introduction activities',
    securityTraining: 'Security Training',
    securityTrainingDescription: 'IT security and data protection training',
    taskRules: 'Task Rules',
    enableTaskDependencies: 'Enable Task Dependencies',
    taskDependenciesDescription: 'Allow tasks to be dependent on completion of other tasks',
    enableTaskReminders: 'Enable Task Reminders',
    taskRemindersDescription: 'Send automated reminders for upcoming and overdue tasks',
    escalateDelayedTasks: 'Escalate Delayed Tasks',
    escalateTasksDescription: 'Automatically escalate overdue tasks to managers',
    showTaskProgressBar: 'Show Task Progress Bar',
    progressBarDescription: 'Display visual progress indicators for tasks',
    systemIntegrations: 'System Integrations',
    hrmsIntegrationDescription: 'Connect with HR Management System to sync employee data',
    azureAdIntegrationDescription: 'Connect with Azure Active Directory for user accounts',
    googleWorkspaceDescription: 'Connect with Google Workspace for email and collaboration',
    slackIntegrationDescription: 'Connect with Slack for notifications and updates',
    gosiApiIntegrationDescription: 'Connect with GOSI API for automatic registration',
    absherIntegrationDescription: 'Connect with Absher Business for government services',
    connected: 'Connected',
    notConnected: 'Not Connected',
    disconnect: 'Disconnect',
    connect: 'Connect',
    addCustomIntegration: 'Add Custom Integration',
    apiSettings: 'API Settings',
    enableApiAccess: 'Enable API Access',
    apiAccessDescription: 'Allow external systems to connect to the onboarding system via API',
    apiKey: 'API Key',
    apiKeyDescription: 'Use this key to authenticate API requests',
    viewApiDocumentation: 'View API Documentation',
    userAccess: 'User Access',
    addUser: 'Add User',
    user: 'User',
    role: 'Role',
    lastActive: 'Last Active',
    editAccess: 'Edit Access',
    changeRole: 'Change Role',
    removeAccess: 'Remove Access',
    userAccessTable: 'User Access Table',
    securitySettings: 'Security Settings',
    enforceDataEncryption: 'Enforce Data Encryption',
    dataEncryptionDescription: 'Encrypt sensitive onboarding data and documents',
    enableAuditLogs: 'Enable Audit Logs',
    auditLogsDescription: 'Track all changes and actions in the system',
    enforceTwoFactorAuth: 'Enforce Two-Factor Authentication',
    twoFactorDescription: 'Require two-factor authentication for access',
    limitDocumentAccess: 'Limit Document Access',
    documentAccessDescription: 'Restrict document access based on user roles',
    recommended: 'Recommended',
    
    // Onboarding View Modal translations
    onboardingDetails: 'Onboarding Details',
    details: 'Details',
    tasks: 'Tasks',
    documents: 'Documents', 
    notes: 'Notes',
    employeeInformation: 'Employee Information',
    keyContacts: 'Key Contacts',
    onboardingTasks: 'Onboarding Tasks',
    requiredDocuments: 'Required Documents',
    activityAndNotes: 'Activity & Notes',
    writeANote: 'Write a note...',
    saveNote: 'Save Note',
    addNote: 'Add Note',
    addTask: 'Add Task',
    addDocument: 'Add Document',
    contact: 'Contact',
    downloadDocument: 'Download',
    hrManager: 'HR Manager',
    departmentManager: 'Department Manager',
    verified: 'Verified',
    uploaded: 'Uploaded',
    pending: 'Pending',
    inProgress: 'In Progress',
    completed: 'Completed',
    
    // Edit mode translations
    editOnboarding: 'Edit Onboarding',
    editOnboardingDesc: 'Update the onboarding details for this employee',
    saveChanges: 'Save Changes',
    
    // New translations for onboarding view and edit functionality
    en: {
      // ... existing translations ...
      
      // Onboarding View Modal translations
      onboardingDetails: 'Onboarding Details',
      details: 'Details',
      tasks: 'Tasks',
      documents: 'Documents', 
      notes: 'Notes',
      employeeInformation: 'Employee Information',
      keyContacts: 'Key Contacts',
      onboardingTasks: 'Onboarding Tasks',
      requiredDocuments: 'Required Documents',
      activityAndNotes: 'Activity & Notes',
      writeANote: 'Write a note...',
      saveNote: 'Save Note',
      addNote: 'Add Note',
      addTask: 'Add Task',
      addDocument: 'Add Document',
      contact: 'Contact',
      downloadDocument: 'Download',
      hrManager: 'HR Manager',
      departmentManager: 'Department Manager',
      verified: 'Verified',
      uploaded: 'Uploaded',
      pending: 'Pending',
      inProgress: 'In Progress',
      completed: 'Completed',
      
      // Edit mode translations
      editOnboarding: 'Edit Onboarding',
      editOnboardingDesc: 'Update the onboarding details for this employee',
      saveChanges: 'Save Changes',
      
      // Add new translations for the assigned tasks view
      myAssignedTasks: 'My Onboarding Tasks',
      myAssignedTasksDesc: 'Manage and update tasks assigned to you for this employee onboarding process.',
      assignedTasksTable: 'Onboarding Tasks',
      noAssignedTasks: 'No tasks are currently assigned to you for this onboarding process',
      markAsComplete: 'Mark as Complete',
      viewDetails: 'View Task Details',
      attachFile: 'Attach Supporting Document',
      addComment: 'Add Comment',
      markAsBlocked: 'Flag as Blocked',
      updateTaskStatus: 'Update Task Progress',
      taskCompletion: 'Task Completion Percentage',
      statusUpdateNote: 'Progress Update Note',
      addNoteAboutThisUpdate: 'Add a note about what you\'ve completed or any issues you\'ve encountered...',
      markingAsComplete: 'Task Will Be Marked Complete',
      completeTaskNotification: 'The employee and onboarding manager will be notified that this task has been completed.',
      updateStatus: 'Save Progress Update',
      addTask: 'Create New Task',
      pending: 'Not Started',
      inProgress: 'In Progress',
      completed: 'Completed',
      blocked: 'Blocked',
      high: 'High',
      medium: 'Medium',
      low: 'Low',
      filter: 'Filter Tasks',
      search: 'Search Tasks',
      searchByTaskOrEmployee: 'Search by task name or assignee...',
      export: 'Export Report',
      exportCSV: 'Export to Excel (CSV)',
      exportPDF: 'Export to PDF Document',
      markComplete: 'Mark as Complete',
    },
    
    ar: {
      // ... existing translations ...
      
      // Onboarding View Modal translations 
      onboardingDetails: 'تفاصيل التأهيل',
      details: 'التفاصيل',
      tasks: 'المهام',
      documents: 'المستندات',
      notes: 'الملاحظات',
      employeeInformation: 'معلومات الموظف',
      keyContacts: 'جهات الاتصال الرئيسية',
      onboardingTasks: 'مهام التأهيل',
      requiredDocuments: 'المستندات المطلوبة',
      activityAndNotes: 'النشاط والملاحظات',
      writeANote: 'اكتب ملاحظة...',
      saveNote: 'حفظ الملاحظة',
      addNote: 'إضافة ملاحظة',
      addTask: 'إضافة مهمة',
      addDocument: 'إضافة مستند',
      contact: 'اتصال',
      downloadDocument: 'تنزيل',
      hrManager: 'مدير الموارد البشرية',
      departmentManager: 'مدير القسم',
      verified: 'تم التحقق',
      uploaded: 'تم الرفع',
      pending: 'قيد الانتظار',
      inProgress: 'قيد التنفيذ',
      completed: 'مكتمل',
      
      // Edit mode translations
      editOnboarding: 'تعديل عملية التأهيل',
      editOnboardingDesc: 'تحديث تفاصيل التأهيل لهذا الموظف',
      saveChanges: 'حفظ التغييرات',
      
      // Add new translations for the assigned tasks view
      myAssignedTasks: 'مهامي المُسندة',
      myAssignedTasksDesc: 'عرض وتحديث جميع المهام المخصصة لك',
      assignedTasksTable: 'جدول المهام المخصصة',
      noAssignedTasks: 'لا توجد مهام مخصصة لك حالياً',
      markAsComplete: 'وضع علامة مكتمل',
      viewDetails: 'عرض التفاصيل',
      attachFile: 'إرفاق ملف',
      addComment: 'إضافة تعليق',
      markAsBlocked: 'وضع علامة معاق',
      updateTaskStatus: 'تحديث حالة المهمة',
      taskCompletion: 'نسبة إكمال المهمة',
      statusUpdateNote: 'ملاحظة تحديث الحالة',
      addNoteAboutThisUpdate: 'أضف ملاحظة حول هذا التحديث',
      markingAsComplete: 'وضع علامة مكتمل على المهمة',
      completeTaskNotification: 'سيتم إخطار الموظف ومسؤول التأهيل بأنك أكملت هذه المهمة.',
      updateStatus: 'تحديث الحالة',
      blocked: 'معاق',
      assignedTasks: 'المهام المُسندة',
      export: 'تصدير',
      exportCSV: 'تصدير إلى CSV',
      exportPDF: 'تصدير إلى PDF',
    },
    
    // Add new translations for the My Tasks section
    en: {
      // ... existing translations ...
      
      myTasks: 'My Tasks',
      manageYourAssignedOnboardingTasks: 'Manage all tasks assigned to you across different onboarding processes',
    },
    
    ar: {
      // ... existing translations ...
      
      myTasks: 'مهامي',
      manageYourAssignedOnboardingTasks: 'إدارة جميع المهام المخصصة لك عبر عمليات التأهيل المختلفة',
    },
    
    // Add new translations for task type specific fields
    en: {
      // ... existing translations ...
      
      // Document Task Type
      documentDetails: 'Document Details',
      documentType: 'Document Type',
      identificationDocuments: 'Identification Documents',
      employmentContract: 'Employment Contract',
      financialDocuments: 'Financial Documents',
      educationalCertificates: 'Educational Certificates',
      medicalRecords: 'Medical Records',
      verificationFlow: 'Verification Flow',
      standardVerification: 'Standard Verification',
      expressVerification: 'Express Verification',
      externalVerification: 'External Verification',
      requiredSignatures: 'Required Signatures',
      documentOptions: 'Document Options',
      needsNotarization: 'Needs Notarization',
      needsTranslation: 'Needs Translation',
      confidentialDocument: 'Confidential Document',
      documentTemplateAvailable: 'Document template is available for this task',
      viewTemplate: 'View Template',
      
      // Meeting Task Type
      meetingDetails: 'Meeting Details',
      meetingDuration: 'Duration (minutes)',
      enterDurationInMinutes: 'Enter duration in minutes',
      minutes: 'minutes',
      meetingTime: 'Meeting Time',
      selectTime: 'Select time',
      meetingType: 'Meeting Type',
      virtual: 'Virtual',
      inPerson: 'In Person',
      hybrid: 'Hybrid',
      meetingLink: 'Meeting Link',
      enterMeetingLink: 'Enter virtual meeting link',
      meetingLocation: 'Meeting Location',
      enterPhysicalLocation: 'Enter physical location',
      meetingAgenda: 'Agenda',
      enterMeetingAgenda: 'Enter meeting agenda items',
      additionalMeetingOptions: 'Additional Options',
      sendCalendarInvite: 'Send Calendar Invite',
      recordMeeting: 'Record Meeting',
      requiresPreparation: 'Requires Preparation',
      
      // Tech Setup Task Type
      techSetupDetails: 'Tech Setup Details',
      hardwareRequirements: 'Hardware Requirements',
      laptop: 'Laptop/Computer',
      monitor: 'Monitor/Display',
      keyboard: 'Keyboard',
      mouse: 'Mouse/Pointing Device',
      headset: 'Headset/Microphone',
      phone: 'Phone/Communication Device',
      additionalHardware: 'Additional Hardware',
      specifyAdditionalHardware: 'Specify additional hardware needed',
      softwareRequirements: 'Software Requirements',
      emailSetup: 'Email Setup',
      vpnAccess: 'VPN Access',
      messagingTools: 'Messaging Tools (e.g., Teams, Slack)',
      cloudStorage: 'Cloud Storage',
      companyERP: 'Company ERP Access',
      companyCRM: 'Company CRM Access',
      additionalSoftware: 'Additional Software',
      specifyAdditionalSoftware: 'Specify any additional software or tools required',
      accessPermissions: 'Access Permissions',
      accessLevel: 'Access Level',
      basicAccess: 'Basic Access',
      standardAccess: 'Standard Access',
      elevatedAccess: 'Elevated Access',
      adminAccess: 'Admin Access',
      networkDrives: 'Shared Drives Access',
      databases: 'Database Access',
      servers: 'Server Access',
      accessRequiresApproval: '🔒 Elevated access requires manager approval',
      itRequestPriority: 'IT Request Priority',
      withinOneWeek: 'Within one week',
      within48Hours: 'Within 48 hours',
      within24Hours: 'Within 24 hours',
      immediate: 'Immediate attention',
      
      // Manual Task Type
      manualTaskDetails: 'Manual Task Details',
      taskCategory: 'Task Category',
      paperwork: 'Paperwork',
      facilityAccess: 'Facility Access',
      officeSupplies: 'Office Supplies',
      transportation: 'Transportation',
      other: 'Other',
      estimatedDuration: 'Estimated Duration',
      enterDuration: 'Enter duration',
      physicalLocation: 'Physical Location',
      mainOffice: 'Main Office',
      branchOffice1: 'Branch Office - East',
      branchOffice2: 'Branch Office - West',
      warehouse: 'Warehouse',
      otherLocation: 'Other Location',
      stepByStepInstructions: 'Step-by-step Instructions',
      enterInstructions: 'Enter detailed instructions',
      completionVerification: 'Completion Verification',
      selfReported: 'Self-reported Completion',
      managerApproval: 'Manager Approval',
      photoEvidence: 'Photo Evidence',
      documentUpload: 'Document Upload',
      manualTaskRequiresInPersonPresence: 'This task requires in-person presence',
      
      // Video Task Type
      videoTrainingDetails: 'Video Training Details',
      videoTitle: 'Video Title',
      enterVideoTitle: 'Enter video title',
      videoDuration: 'Video Duration',
      enterVideoDuration: 'Enter duration',
      videoCategory: 'Video Category',
      companyOrientation: 'Company Orientation',
      complianceTraining: 'Compliance Training',
      softwareTraining: 'Software Training',
      safetyTraining: 'Safety Training',
      productTraining: 'Product Training',
      videoSource: 'Video Source',
      internalLibrary: 'Internal Library',
      externalLink: 'External Link',
      learningManagementSystem: 'Learning Management System',
      internalVideo: 'Internal Video',
      selectFromLibrary: 'Select from library',
      companyIntroduction: 'Company Introduction',
      companyPolicies: 'Company Policies',
      safetyProcedures: 'Safety Procedures',
      companySystems: 'Company Systems',
      companyValues: 'Company Values',
      videoURL: 'Video URL',
      enterVideoLink: 'Enter video link',
      courseCode: 'Course Code',
      enterCourseCode: 'Enter course code',
      moduleNumber: 'Module Number',
      enterModuleNumber: 'Enter module number',
      completionRequirements: 'Completion Requirements',
      completionQuiz: 'Completion Quiz',
      requiresCertificate: 'Requires Certificate',
      trackWatchTime: 'Track Watch Time',
      quizWillBeRequiredAfterVideo: 'A quiz will be required after watching the video',
      setupQuiz: 'Setup Quiz',
      
      // Toggle additional fields
      hideDetails: 'Hide Details',
      showDetails: 'Show Details',
    },
    
    ar: {
      // ... existing translations ...
      
      // Document Task Type
      documentDetails: 'تفاصيل المستند',
      documentType: 'نوع المستند',
      identificationDocuments: 'وثائق الهوية',
      employmentContract: 'عقد العمل',
      financialDocuments: 'المستندات المالية',
      educationalCertificates: 'الشهادات التعليمية',
      medicalRecords: 'السجلات الطبية',
      verificationFlow: 'مسار التحقق',
      standardVerification: 'التحقق القياسي',
      expressVerification: 'التحقق السريع',
      externalVerification: 'التحقق الخارجي',
      requiredSignatures: 'التوقيعات المطلوبة',
      documentOptions: 'خيارات المستند',
      needsNotarization: 'يحتاج إلى توثيق',
      needsTranslation: 'يحتاج إلى ترجمة',
      confidentialDocument: 'مستند سري',
      documentTemplateAvailable: 'نموذج المستند متاح لهذه المهمة',
      viewTemplate: 'عرض النموذج',
      
      // Meeting Task Type
      meetingDetails: 'تفاصيل الاجتماع',
      meetingDuration: 'المدة (بالدقائق)',
      enterDurationInMinutes: 'أدخل المدة بالدقائق',
      minutes: 'دقائق',
      meetingTime: 'وقت الاجتماع',
      selectTime: 'حدد الوقت',
      meetingType: 'نوع الاجتماع',
      virtual: 'افتراضي',
      inPerson: 'حضوري',
      hybrid: 'مختلط',
      meetingLink: 'رابط الاجتماع',
      enterMeetingLink: 'أدخل رابط الاجتماع الافتراضي',
      meetingLocation: 'موقع الاجتماع',
      enterPhysicalLocation: 'أدخل الموقع الفعلي',
      meetingAgenda: 'جدول أعمال',
      enterMeetingAgenda: 'أدخل بنود جدول الأعمال',
      additionalMeetingOptions: 'خيارات إضافية',
      sendCalendarInvite: 'إرسال دعوة التقويم',
      recordMeeting: 'تسجيل الاجتماع',
      requiresPreparation: 'يتطلب تحضير',
      
      // Tech Setup Task Type
      techSetupDetails: 'تفاصيل الإعداد التقني',
      hardwareRequirements: 'متطلبات الأجهزة',
      laptop: 'الحاسوب المحمول',
      monitor: 'شاشة العرض',
      keyboard: 'لوحة المفاتيح',
      mouse: 'الفأرة',
      headset: 'سماعة الرأس/الميكروفون',
      phone: 'الهاتف/جهاز الاتصال',
      additionalHardware: 'أجهزة إضافية',
      specifyAdditionalHardware: 'حدد الأجهزة الإضافية المطلوبة',
      softwareRequirements: 'متطلبات البرمجيات',
      emailSetup: 'إعداد البريد الإلكتروني',
      vpnAccess: 'الوصول إلى VPN',
      messagingTools: 'أدوات المراسلة (مثل Teams، Slack)',
      cloudStorage: 'التخزين السحابي',
      companyERP: 'الوصول إلى نظام تخطيط موارد الشركة',
      companyCRM: 'الوصول إلى نظام إدارة علاقات العملاء',
      additionalSoftware: 'برمجيات إضافية',
      specifyAdditionalSoftware: 'حدد أي برامج أو أدوات إضافية مطلوبة',
      accessPermissions: 'أذونات الوصول',
      accessLevel: 'مستوى الوصول',
      basicAccess: 'وصول أساسي',
      standardAccess: 'وصول قياسي',
      elevatedAccess: 'وصول متقدم',
      adminAccess: 'وصول المسؤول',
      networkDrives: 'الوصول إلى محركات الأقراص المشتركة',
      databases: 'الوصول إلى قواعد البيانات',
      servers: 'الوصول إلى الخوادم',
      accessRequiresApproval: '🔒 يتطلب الوصول المرتفع موافقة المدير',
      itRequestPriority: 'أولوية طلب تكنولوجيا المعلومات',
      withinOneWeek: 'خلال أسبوع واحد',
      within48Hours: 'خلال 48 ساعة',
      within24Hours: 'خلال 24 ساعة',
      immediate: 'اهتمام فوري',
      
      // Manual Task Type
      manualTaskDetails: 'تفاصيل المهمة اليدوية',
      taskCategory: 'فئة المهمة',
      paperwork: 'وراق',
      facilityAccess: 'وصول المنشأة',
      officeSupplies: 'مستلزمات المكتب',
      transportation: 'النقل',
      other: 'أخرى',
      estimatedDuration: 'المدة المقدرة',
      enterDuration: 'أدخل المدة',
      physicalLocation: 'الموقع الفعلي',
      mainOffice: 'المكتب الرئيسي',
      branchOffice1: 'المكتب الفرعي - الشرق',
      branchOffice2: 'المكتب الفرعي - الغرب',
      warehouse: 'المستودع',
      otherLocation: 'موقع آخر',
      stepByStepInstructions: 'تعليمات خطوة بخطوة',
      enterInstructions: 'أدخل تعليمات مفصلة',
      completionVerification: 'التحقق من الإكمال',
      selfReported: 'إبلاغ ذاتي بالإكمال',
      managerApproval: 'موافقة المدير',
      photoEvidence: 'دليل بالصور',
      documentUpload: 'رفع المستندات',
      manualTaskRequiresInPersonPresence: 'تتطلب هذه المهمة الحضور الشخصي',
      
      // Video Task Type
      videoTrainingDetails: 'تفاصيل التدريب بالفيديو',
      videoTitle: 'عنوان الفيديو',
      enterVideoTitle: 'أدخل عنوان الفيديو',
      videoDuration: 'مدة الفيديو',
      enterVideoDuration: 'أدخل المدة',
      videoCategory: 'فئة الفيديو',
      companyOrientation: 'التوجيه',
      complianceTraining: 'تدريب الامتثال',
      softwareTraining: 'تدريب البرمجيات',
      safetyTraining: 'تدريب السلامة',
      productTraining: 'تدريب المنتج',
      videoSource: 'مصدر الفيديو',
      internalLibrary: 'المكتبة الداخلية',
      externalLink: 'رابط خارجي',
      learningManagementSystem: 'نظام إدارة التعلم',
      internalVideo: 'فيديو داخلي',
      selectFromLibrary: 'اختر من المكتبة',
      companyIntroduction: 'مقدمة الشركة',
      companyPolicies: 'سياسات الشركة',
      safetyProcedures: 'إجراءات السلامة',
      companySystems: 'أنظمة الشركة',
      companyValues: 'قيم الشركة',
      videoURL: 'رابط الفيديو',
      enterVideoLink: 'أدخل رابط الفيديو',
      courseCode: 'رمز الدورة',
      enterCourseCode: 'أدخل رمز الدورة',
      moduleNumber: 'رقم الوحدة',
      enterModuleNumber: 'أدخل رقم الوحدة',
      completionRequirements: 'متطلبات الإكمال',
      completionQuiz: 'اختبار الإكمال',
      requiresCertificate: 'يتطلب شهادة',
      trackWatchTime: 'تتبع وقت المشاهدة',
      quizWillBeRequiredAfterVideo: 'سيكون هناك اختبار مطلوب بعد مشاهدة الفيديو',
      setupQuiz: 'إعداد الاختبار',
      
      // Toggle additional fields
      hideDetails: 'إخفاء التفاصيل',
      showDetails: 'عرض التفاصيل',
    },
  },
  ar: {
    welcomeToWise: 'مرحبًا بك في وايز',
    recruitment: 'التوظيف',
    analytics: 'التحليلات',
    jobRequisition: 'طلب الوظيفة',
    candidate: 'المرشح',
    interview: 'المقابلة',
    offer: 'العرض',
    onboarding: 'التأهيل',
    careersPortalSetup: 'إعداد بوابة الوظائف',
    contentComingSoon: 'المحتوى قادم قريبًا',
    collapse: 'طي',
    // Onboarding module translations (Arabic)
    onboardingManagement: 'إدارة التأهيل',
    startOnboarding: 'بدء التأهيل',
    dashboard: 'لوحة المعلومات',
    activeOnboarding: 'التأهيل النشط',
    completedOnboarding: 'التأهيل المكتمل',
    templates: 'القوالب',
    settings: 'الإعدادات',
    onboardingSettings: 'إعدادات التأهيل',
    settingsDescription: 'ضبط إعدادات التأهيل الافتراضية وتفضيلات الإشعارات وإعدادات الامتثال.',
    totalOnboardings: 'إجمالي عمليات التأهيل',
    thisMonth: 'هذا الشهر',
    ytd: 'منذ بداية العام',
    completionRate: 'معدل الإكمال',
    averagePerEmployee: 'المتوسط لكل موظف',
    targetRate: 'المعدل المستهدف',
    delayedTasks: 'المهام المتأخرة',
    requiresAttention: 'تتطلب الانتباه',
    critical: 'حرجة',
    activeTemplates: 'القوالب النشطة',
    mostUsed: 'الأكثر استخدامًا',
    department: 'القسم',
    onboardingProgress: 'تقدم التأهيل',
    aiInsights: 'رؤى الذكاء الاصطناعي',
    aiInsight1: 'معدل إكمال التأهيل في قسم تقنية المعلومات بلغ 92٪، وهو أعلى من متوسط الشركة.',
    aiInsight2: 'مهام تقديم المستندات لديها أعلى معدل تأخير (23٪).',
    aiInsight3: 'ضع في اعتبارك إضافة مهمة "الوصول إلى النظام" إلى قالب المالية استنادًا إلى بيانات الشركات المماثلة.',
    taskCompletionByType: 'إكمال المهام حسب النوع',
    adminTasks: 'المهام الإدارية',
    complianceTasks: 'مهام الامتثال',
    trainingTasks: 'مهام التدريب',
    techSetupTasks: 'مهام الإعداد التقني',
    orientationTasks: 'مهام التوجيه',
    upcomingDeadlines: 'المواعيد النهائية القادمة',
    searchEmployeeDepartment: 'البحث حسب الموظف أو القسم',
    newTemplate: 'قالب جديد',
    filter: 'تصفية',
    allDepartments: 'جميع الأقسام',
    finance: 'المالية',
    sales: 'المبيعات',
    employee: 'الموظف',
    templateName: 'اسم القالب',
    position: 'المنصب',
    tasksCount: 'عدد المهام',
    owner: 'المالك',
    startDate: 'تاريخ البدء',
    progress: 'التقدم',
    actions: 'الإجراءات',
    noRecordsFound: 'لم يتم العثور على سجلات',
    tasks: 'المهام',
    view: 'عرض',
    edit: 'تعديل',
    duplicate: 'نسخ',
    delete: 'حذف',
    sendReminder: 'إرسال تذكير',
    markComplete: 'تحديد كمكتمل',
    reassign: 'إعادة تعيين',
    archive: 'أرشفة',
    completed: 'مكتمل',
    inProgress: 'قيد التنفيذ',
    ongoing: 'مستمر',
    justStarted: 'بدأ للتو',
    employeeProfile: 'ملف الموظف',
    documents: 'المستندات',
    owner: 'المالك',
    tasks: 'المهام',
    review: 'مراجعة',
    employeeProfileStep: 'ملف الموظف',
    employeeProfileDesc: 'تعبئة أو تأكيد معلومات الموظف',
    fullName: 'الاسم الكامل',
    enterFullName: 'أدخل الاسم الكامل',
    email: 'البريد الإلكتروني',
    enterEmail: 'أدخل البريد الإلكتروني',
    phone: 'الهاتف',
    enterPhone: 'أدخل رقم الهاتف',
    nationalId: 'الهوية الوطنية/الإقامة',
    enterNationalId: 'أدخل رقم الهوية',
    saudiIdOrIqama: 'الهوية السعودية أو الإقامة لغير السعوديين',
    gosiId: 'رقم التأمينات',
    enterGosiId: 'أدخل رقم التأمينات',
    enterPosition: 'أدخل المنصب',
    selectDepartment: 'اختر القسم',
    selectManager: 'اختر المدير',
    selectStartDate: 'اختر تاريخ البدء',
    joiningLocation: 'موقع الانضمام',
    enterLocation: 'أدخل الموقع',
    contractType: 'نوع العقد',
    selectContractType: 'اختر نوع العقد',
    permanent: 'دائم',
    contract: 'بعقد',
    probation: 'فترة تجريبية',
    employeeType: 'نوع الموظف',
    selectEmployeeType: 'اختر نوع الموظف',
    saudiNational: 'مواطن سعودي',
    expat: 'وافد',
    aiProfileCompletionTip: 'قام الذكاء الاصطناعي بإكمال بعض الحقول تلقائيًا استنادًا إلى سجل المرشح. يرجى التحقق من المعلومات.',
    requiredDocumentsStep: 'المستندات المطلوبة',
    requiredDocumentsDesc: 'رفع المستندات اللازمة لتأهيل الموظف',
    document_passport: 'صورة جواز السفر',
    document_nationalId: 'الهوية الوطنية/الإقامة',
    document_certificates: 'الشهادات التعليمية',
    document_bankInfo: 'معلومات الحساب البنكي',
    document_signedOffer: 'خطاب العرض الموقع',
    document_passport_desc: 'نسخة واضحة من صفحة معلومات جواز السفر',
    document_nationalId_desc: 'وجه الهوية الوطنية أو الإقامة وظهرها',
    document_certificates_desc: 'الشهادات الأكاديمية والمهنية',
    document_bankInfo_desc: 'تفاصيل الحساب البنكي لتحويل الراتب',
    document_signedOffer_desc: 'خطاب قبول العرض مكتمل وموقع',
    addCustomDocument: 'إضافة مستند مخصص',
    addFullCycle: 'إضافة دورة كاملة',
    assignOnboardingOwnerStep: 'تعيين مسؤول التأهيل',
    assignOwnerDesc: 'اختر عضوًا في الفريق للإشراف على عملية التأهيل هذه',
    assignOnboardingOwner: 'تعيين مسؤول التأهيل',
    selectOwner: 'اختر المسؤول',
    ownerResponsibilities: 'مسؤوليات المالك',
    ownerResponsibility1: 'توجيه الموظف خلال عملية التأهيل',
    ownerResponsibility2: 'ضمان إكمال جميع المهام المطلوبة في الوقت المحدد',
    ownerResponsibility3: 'حل المشكلات التي قد تنشأ أثناء التأهيل',
    ownerResponsibility4: 'تقديم تحديثات منتظمة للموارد البشرية والإدارة',
    aiOwnerSuggestion: 'بناءً على القسم والدور، يقترح الذكاء الاصطناعي تعيين أخصائية الموارد البشرية سارة القحطاني كمسؤول للتأهيل.',
    setupOnboardingTasksStep: 'إعداد مهام التأهيل',
    setupTasksDesc: 'إنشاء المهام التي يجب إكمالها خلال عملية التأهيل',
    totalTasks: 'إجمالي المهام',
    taskTypeDistribution: 'المهام موزعة حسب النوع والأولوية',
    useTemplate: 'استخدام القالب',
    addTask: 'إضافة مهمة',
    noDueDate: 'لا يوجد موعد نهائي',
    assignedTo: 'مخصص إلى',
    marketing: 'التسويق',
    reviewAndConfirmStep: 'المراجعة والتأكيد',
    reviewAndConfirmDesc: 'مراجعة جميع تفاصيل التأهيل قبل الإنهاء',
    employeeDetails: 'تفاصيل الموظف',
    name: 'الاسم',
    allUploaded: 'تم رفع الكل',
    uploaded: 'تم الرفع',
    notAssigned: 'غير معين',
    tasksSummary: 'ملخص المهام',
    addMore: 'إضافة المزيد',
    previousStep: 'الخطوة السابقة',
    nextStep: 'الخطوة التالية',
    createOnboarding: 'إنشاء التأهيل',
    saveAsDraft: 'حفظ كمسودة',
    cancel: 'إلغاء',
    aiSuggestion: 'اقتراح الذكاء الاصطناعي',
    aiOnboardingSuggestionText: 'بناءً على ملف الموظف (قسم تقنية المعلومات، وضع الوافد)، ضع في اعتبارك إضافة مهام للتحقق من تصريح العمل والتدريب على الوصول إلى أنظمة تقنية المعلومات.',
    additionalNotes: 'ملاحظات إضافية',
    enterAdditionalNotes: 'أدخل أي ملاحظات إضافية لعملية التأهيل هذه',
    onboardingWizard: 'معالج التأهيل',
    onboardingWizardDesc: 'إنشاء رحلة تأهيل منظمة لموظفك الجديد',
    onboardingProgress: 'تقدم التأهيل',
    step: 'خطوة',
    of: 'من',
    createNewTask: 'إنشاء مهمة جديدة',
    taskTitle: 'عنوان المهمة',
    enterTaskTitle: 'أدخل عنوان المهمة',
    taskType: 'نوع المهمة',
    selectTaskType: 'اختر نوع المهمة',
    admin: 'اداري',
    compliance: 'امتثال',
    training: 'تدريب',
    techSetup: 'إعداد تقني',
    orientation: 'توحيد',
    dueDate: 'الموعد النهائي',
    selectDueDate: 'اختر الموعد النهائي',
    taskDescription: 'وصف المهمة',
    enterTaskDescription: 'أدخل وصف المهمة',
    attachFile: 'إرفاق ملف',
    addLink: 'إضافة رابط',
    completeGOSIRegistration: 'إكمال تسجيل التأمينات',
    setupEmailAccount: 'إعداد حساب البريد الإلكتروني',
    completeOrientationTraining: 'إكمال تدريب التوجيه',
    signEmploymentContract: 'توقيع عقد العمل',
    submitBankDetails: 'تقديم تفاصيل البنك',
    overdue: 'متأخر',
    onTrack: 'في المسار الصحيح',
    required: 'مطلوب',
    upload: 'رفع',
    preview: 'معاينة',
    change: 'تغيير',
    onboardingListTable: 'جدول قائمة التأهيل',
    month: 'الشهر',
    totalCompletion: 'الإكمال الكلي',
    
    // New translations for candidate auto-loading feature
    candidateInfoAutoLoaded: 'تم تحميل معلومات المرشح مسبقًا. يرجى التحقق والتحديث حسب الحاجة.',
    loadingCandidateInfo: 'جاري تحميل معلومات المرشح...',
    candidateInfoEditableNote: 'يمكن تحديث جميع معلومات المرشح المحملة مسبقًا إذا لزم الأمر قبل المتابعة.',
    
    // Add new translations for candidate selection
    selectCandidate: 'اختر المرشح',
    selectCandidateToOnboard: 'اختر مرشحًا للتأهيل',
    candidateSelected: 'تم اختيار المرشح',
    
    // Add new translations for task editing
    editTask: 'تعديل المهمة',
    saveChanges: 'حفظ التغييرات',
    assignTo: 'تعيين إلى',
    selectAssignee: 'اختر المكلف',
    taskPriority: 'أولوية المهمة',
    low: 'منخفضة',
    medium: 'متوسطة',
    high: 'عالية',
    markAsRequired: 'تحديد كضروري',
    
    // Add template selection translations
    selectOnboardingTemplate: 'اختر قالب التأهيل',
    selectTemplateInstructions: 'اختر قالبًا لإضافة مهام محددة مسبقًا بسرعة لعملية التأهيل هذه.',
    fullCycleTemplateDescription: 'موصى به: يشمل مهام إدارية وامتثال وتدريب وإعداد تقني لتجربة تأهيل كاملة.',
    applyTemplate: 'تطبيق القالب',
    
    // Add new document-related translations
    documentName: 'اسم المستند',
    enterDocumentName: 'أدخل اسم المستند',
    documentDescription: 'وصف المستند',
    enterDocumentDescription: 'أدخل وصف المستند',
    addDocument: 'إضافة مستند',
    
    // Add new translations to the English translations object
    createNewTemplate: 'إنشاء قالب جديد',
    enterTemplateName: 'أدخل اسم القالب',
    assignOwner: 'تعيين المسؤول',
    selectTaskTypes: 'اختر أنواع المهام',
    templateDescription: 'وصف القالب',
    enterTemplateDescription: 'أدخل وصف القالب',
    requiredDocuments: 'المستندات المطلوبة',
    saveAndContinue: 'حفظ ومتابعة',
    
    // Add new settings-related translations to the English translations object
    saveSettings: 'حفظ الإعدادات',
    generalSettings: 'الإعدادات العامة',
    notificationSettings: 'إعدادات الإشعارات',
    complianceSettings: 'إعدادات الامتثال',
    taskSettings: 'إعدادات المهام',
    integrations: 'التكاملات',
    accessControl: 'التحكم في الوصول',
    defaultSettings: 'الإعدادات الافتراضية',
    defaultOnboardingDuration: 'المدة الافتراضية للتأهيل',
    days: 'أيام',
    durationDescription: 'المدة الافتراضية لإكمال عملية التأهيل',
    defaultTemplate: 'القالب الافتراضي',
    selectDefaultTemplate: 'اختر القالب الافتراضي',
    defaultOwner: 'المسؤول الافتراضي',
    selectDefaultOwner: 'اختر المسؤول الافتراضي',
    autoAssignBasedOnDepartment: 'تعيين تلقائي حسب القسم',
    defaultOnboardingLanguage: 'لغة التأهيل الافتراضية',
    selectLanguage: 'اختر اللغة',
    automationSettings: 'إعدادات الأتمتة',
    enableAutomation: 'تمكين الأتمتة',
    automationDescription: 'تعيين المهام تلقائيًا بناءً على دور وقسم الموظف',
    sendWelcomeEmail: 'إرسال بريد الترحيب',
    welcomeEmailDescription: 'إرسال بريد ترحيب تلقائيًا عند بدء التأهيل',
    enableAiSuggestions: 'تمكين اقتراحات الذكاء الاصطناعي',
    aiSuggestionsDescription: 'استخدام الذكاء الاصطناعي لاقتراح مهام وتدفقات عمل التأهيل المثلى',
    new: 'جديد',
    emailNotifications: 'إشعارات البريد الإلكتروني',
    defaultFrequency: 'التكرار الافتراضي',
    immediately: 'فورًا',
    dailyDigest: 'ملخص يومي',
    weeklyDigest: 'ملخص أسبوعي',
    onboardingStartNotification: 'بدء التأهيل',
    onboardingStartDescription: 'عند بدء عملية تأهيل جديدة',
    taskAssignedNotification: 'تم تعيين المهمة',
    taskAssignedDescription: 'عند تعيين مهمة لمستخدم',
    taskDueNotification: 'المهمة قريبة من الموعد النهائي',
    taskDueDescription: 'عندما تقترب المهمة من موعد نهائيها',
    documentUploadedNotification: 'تم رفع المستند',
    documentUploadedDescription: 'عند رفع مستند إلى النظام',
    onboardingCompleteNotification: 'اكتمال التأهيل',
    onboardingCompleteDescription: 'عند اكتمال عملية التأهيل',
    taskOverdueNotification: 'المهمة متأخرة',
    taskOverdueDescription: 'عندما تصبح المهمة متأخرة',
    managerApprovalNotification: 'موافقة المدير',
    managerApprovalDescription: 'عندما تكون هناك حاجة إلى موافقة المدير',
    systemNotifications: 'إشعارات النظام',
    enableInAppNotifications: 'تمكين الإشعارات داخل التطبيق',
    inAppNotificationsDescription: 'عرض الإشعارات داخل التطبيق',
    enablePushNotifications: 'تمكين الإشعارات المنبثقة',
    pushNotificationsDescription: 'إرسال إشعارات إلى سطح المكتب أو الجهاز المحمول',
    enableSlackNotifications: 'تمكين إشعارات سلاك',
    slackNotificationsDescription: 'إرسال إشعارات إلى قنوات سلاك المتصلة',
    enableSmsNotifications: 'تمكين إشعارات الرسائل القصيرة',
    smsNotificationsDescription: 'إرسال إشعارات الرسائل النصية للأحداث الحرجة',
    reminderSettings: 'إعدادات التذكير',
    sendTaskReminders: 'إرسال تذكيرات المهام',
    taskRemindersSettingDescription: 'متى يتم إرسال تذكيرات للمهام القادمة',
    oneDayBefore: 'قبل يوم واحد',
    threeDaysBefore: 'قبل 3 أيام',
    oneWeekBefore: 'قبل أسبوع واحد',
    custom: 'مخصص',
    sendEscalationNotifications: 'إرسال إشعارات التصعيد',
    escalationNotificationsDescription: 'متى يتم تصعيد المهام المتأخرة إلى المديرين',
    oneDay: 'بعد يوم واحد من الموعد النهائي',
    twoDays: 'بعد يومين من الموعد النهائي',
    threeDays: 'بعد 3 أيام من الموعد النهائي',
    oneWeek: 'بعد أسبوع من الموعد النهائي',
    never: 'أبدًا',
    documentRequirements: 'متطلبات المستندات',
    documentType: 'نوع المستند',
    required: 'مطلوب',
    defaultForAll: 'افتراضي للجميع',
    appliesTo: 'ينطبق على',
    actions: 'الإجراءات',
    allEmployees: 'جميع الموظفين',
    expatsOnly: 'الوافدون فقط',
    documentWorkPermit: 'تصريح العمل',
    employmentContract: 'عقد العمل',
    medicalInsurance: 'شهادة التأمين الطبي',
    addDocumentType: 'إضافة نوع مستند',
    documentRequirementsNote: 'يجب رفع المستندات المحددة كضرورية قبل اكتمال التأهيل. سيتم تضمين المستندات الافتراضية تلقائيًا في جميع عمليات التأهيل الجديدة.',
    complianceRules: 'قواعد الامتثال',
    enforceDocumentExpiration: 'تطبيق انتهاء صلاحية المستندات',
    documentExpirationDescription: 'تتبع تواريخ انتهاء المستندات وإرسال تذكيرات',
    enforceBackgroundChecks: 'تطبيق التحقق من الخلفية',
    backgroundChecksDescription: 'طلب التحقق من الخلفية قبل اكتمال التأهيل',
    enforceSignatureVerification: 'تطبيق التحقق من التوقيع',
    signatureVerificationDescription: 'طلب توقيعات رقمية للمستندات الرئيسية',
    requireManagerApproval: 'طلب موافقة المدير',
    managerApprovalDescription: 'طلب موافقة المدير لإكمال التأهيل',
    localRegulations: 'اللوائح المحلية',
    saudiComplianceInfo: 'متطلبات الامتثال في المملكة العربية السعودية',
    saudiComplianceDescription: 'يشمل تسجيل التأمينات الاجتماعية، ومتطلبات السعودة، والامتثال لوزارة العمل',
    enforceGOSIRegistration: 'تطبيق تسجيل التأمينات',
    gosiComplianceTooltip: 'تسجيل المؤسسة العامة للتأمينات الاجتماعية مطلوب لجميع الموظفين',
    enforceSaudization: 'تطبيق قواعد السعودة',
    saudizationTooltip: 'ضمان الامتثال لمتطلبات توطين الوظائف السعودية',
    taskTypes: 'أنواع المهام',
    addTaskType: 'إضافة نوع مهمة',
    taskType: 'نوع المهمة',
    color: 'اللون',
    description: 'الوصف',
    systemDefault: 'افتراضي النظام',
    save: 'حفظ',
    adminTasksDescription: 'المهام الإدارية مثل الأعمال الورقية وإعداد النظام',
    complianceTasksDescription: 'المهام المتعلقة بالامتثال القانوني والتنظيمي',
    trainingTasksDescription: 'أنشطة تدريب وتطوير الموظفين',
    techSetupTasksDescription: 'مهام إعداد الأنظمة التقنية والأجهزة',
    orientationTasksDescription: 'أنشطة التعريف بالشركة والفريق',
    securityTraining: 'التدريب على الأمان',
    securityTrainingDescription: 'التدريب على أمن تكنولوجيا المعلومات وحماية البيانات',
    taskRules: 'قواعد المهام',
    enableTaskDependencies: 'تمكين تبعيات المهام',
    taskDependenciesDescription: 'السماح بأن تكون المهام معتمدة على إكمال مهام أخرى',
    enableTaskReminders: 'تمكين تذكيرات المهام',
    taskRemindersDescription: 'إرسال تذكيرات آلية للمهام القادمة والمتأخرة',
    escalateDelayedTasks: 'تصعيد المهام المتأخرة',
    escalateTasksDescription: 'تصعيد المهام المتأخرة تلقائيًا إلى المديرين',
    showTaskProgressBar: 'عرض شريط تقدم المهام',
    progressBarDescription: 'عرض مؤشرات التقدم المرئية للمهام',
    systemIntegrations: 'تكاملات النظام',
    hrmsIntegrationDescription: 'الاتصال بنظام إدارة الموارد البشرية لمزامنة بيانات الموظفين',
    azureAdIntegrationDescription: 'الاتصال بـ Azure Active Directory لحسابات المستخدمين',
    googleWorkspaceDescription: 'الاتصال بـ Google Workspace للبريد الإلكتروني والتعاون',
    slackIntegrationDescription: 'الاتصال بـ Slack للإشعارات والتحديثات',
    gosiApiIntegrationDescription: 'الاتصال بواجهة برمجة تطبيقات التأمينات للتسجيل التلقائي',
    absherIntegrationDescription: 'الاتصال بأبشر أعمال للخدمات الحكومية',
    connected: 'متصل',
    notConnected: 'غير متصل',
    disconnect: 'قطع الاتصال',
    connect: 'اتصال',
    addCustomIntegration: 'إضافة تكامل مخصص',
    apiSettings: 'إعدادات واجهة برمجة التطبيقات',
    enableApiAccess: 'تمكين الوصول إلى API',
    apiAccessDescription: 'السماح للأنظمة الخارجية بالاتصال بنظام التأهيل عبر API',
    apiKey: 'مفتاح API',
    apiKeyDescription: 'استخدم هذا المفتاح لمصادقة طلبات API',
    viewApiDocumentation: 'عرض وثائق API',
    userAccess: 'وصول المستخدمين',
    addUser: 'إضافة مستخدم',
    user: 'المستخدم',
    role: 'الدور',
    lastActive: 'آخر نشاط',
    editAccess: 'تعديل الوصول',
    changeRole: 'تغيير الدور',
    removeAccess: 'إزالة الوصول',
    userAccessTable: 'جدول وصول المستخدمين',
    securitySettings: 'إعدادات الأمان',
    enforceDataEncryption: 'تطبيق تشفير البيانات',
    dataEncryptionDescription: 'تشفير بيانات ومستندات التأهيل الحساسة',
    enableAuditLogs: 'تمكين سجلات التدقيق',
    auditLogsDescription: 'تتبع جميع التغييرات والإجراءات في النظام',
    enforceTwoFactorAuth: 'تطبيق المصادقة الثنائية',
    twoFactorDescription: 'طلب المصادقة الثنائية للوصول',
    limitDocumentAccess: 'تقييد الوصول إلى المستندات',
    documentAccessDescription: 'تقييد الوصول إلى المستندات بناءً على أدوار المستخدمين',
    recommended: 'موصى به',
    
    // Onboarding View Modal translations
    onboardingDetails: 'Onboarding Details',
    details: 'Details',
    tasks: 'Tasks',
    documents: 'Documents', 
    notes: 'Notes',
    employeeInformation: 'Employee Information',
    keyContacts: 'Key Contacts',
    onboardingTasks: 'Onboarding Tasks',
    requiredDocuments: 'Required Documents',
    activityAndNotes: 'Activity & Notes',
    writeANote: 'Write a note...',
    saveNote: 'Save Note',
    addNote: 'Add Note',
    addTask: 'Add Task',
    addDocument: 'Add Document',
    contact: 'Contact',
    downloadDocument: 'Download',
    hrManager: 'HR Manager',
    departmentManager: 'Department Manager',
    verified: 'Verified',
    uploaded: 'Uploaded',
    pending: 'Pending',
    inProgress: 'In Progress',
    completed: 'Completed',
    
    // Edit mode translations
    editOnboarding: 'Edit Onboarding',
    editOnboardingDesc: 'Update the onboarding details for this employee',
    saveChanges: 'Save Changes',
    
    // New translations for onboarding view and edit functionality
    en: {
      // ... existing translations ...
      
      // Onboarding View Modal translations
      onboardingDetails: 'Onboarding Details',
      details: 'Details',
      tasks: 'Tasks',
      documents: 'Documents', 
      notes: 'Notes',
      employeeInformation: 'Employee Information',
      keyContacts: 'Key Contacts',
      onboardingTasks: 'Onboarding Tasks',
      requiredDocuments: 'Required Documents',
      activityAndNotes: 'Activity & Notes',
      writeANote: 'Write a note...',
      saveNote: 'Save Note',
      addNote: 'Add Note',
      addTask: 'Add Task',
      addDocument: 'Add Document',
      contact: 'Contact',
      downloadDocument: 'Download',
      hrManager: 'HR Manager',
      departmentManager: 'Department Manager',
      verified: 'Verified',
      uploaded: 'Uploaded',
      pending: 'Pending',
      inProgress: 'In Progress',
      completed: 'Completed',
      
      // Edit mode translations
      editOnboarding: 'Edit Onboarding',
      editOnboardingDesc: 'Update the onboarding details for this employee',
      saveChanges: 'Save Changes',
      
      // Add new translations for the assigned tasks view
      myAssignedTasks: 'My Onboarding Tasks',
      myAssignedTasksDesc: 'Manage and update tasks assigned to you for this employee onboarding process.',
      assignedTasksTable: 'Onboarding Tasks',
      noAssignedTasks: 'No tasks are currently assigned to you for this onboarding process',
      markAsComplete: 'Mark as Complete',
      viewDetails: 'View Task Details',
      attachFile: 'Attach Supporting Document',
      addComment: 'Add Comment',
      markAsBlocked: 'Flag as Blocked',
      updateTaskStatus: 'Update Task Progress',
      taskCompletion: 'Task Completion Percentage',
      statusUpdateNote: 'Progress Update Note',
      addNoteAboutThisUpdate: 'Add a note about what you\'ve completed or any issues you\'ve encountered...',
      markingAsComplete: 'Task Will Be Marked Complete',
      completeTaskNotification: 'The employee and onboarding manager will be notified that this task has been completed.',
      updateStatus: 'Save Progress Update',
      addTask: 'Create New Task',
      pending: 'Not Started',
      inProgress: 'In Progress',
      completed: 'Completed',
      blocked: 'Blocked',
      high: 'High',
      medium: 'Medium',
      low: 'Low',
      filter: 'Filter Tasks',
      search: 'Search Tasks',
      searchByTaskOrEmployee: 'Search by task name or assignee...',
      export: 'Export Report',
      exportCSV: 'Export to Excel (CSV)',
      exportPDF: 'Export to PDF Document',
      markComplete: 'Mark as Complete',
    },
    
    ar: {
      // ... existing translations ...
      
      // Onboarding View Modal translations 
      onboardingDetails: 'تفاصيل التأهيل',
      details: 'التفاصيل',
      tasks: 'المهام',
      documents: 'المستندات',
      notes: 'الملاحظات',
      employeeInformation: 'معلومات الموظف',
      keyContacts: 'جهات الاتصال الرئيسية',
      onboardingTasks: 'مهام التأهيل',
      requiredDocuments: 'المستندات المطلوبة',
      activityAndNotes: 'النشاط والملاحظات',
      writeANote: 'اكتب ملاحظة...',
      saveNote: 'حفظ الملاحظة',
      addNote: 'إضافة ملاحظة',
      addTask: 'إضافة مهمة',
      addDocument: 'إضافة مستند',
      contact: 'اتصال',
      downloadDocument: 'تنزيل',
      hrManager: 'مدير الموارد البشرية',
      departmentManager: 'مدير القسم',
      verified: 'تم التحقق',
      uploaded: 'تم الرفع',
      pending: 'قيد الانتظار',
      inProgress: 'قيد التنفيذ',
      completed: 'مكتمل',
      
      // Edit mode translations
      editOnboarding: 'تعديل عملية التأهيل',
      editOnboardingDesc: 'تحديث تفاصيل التأهيل لهذا الموظف',
      saveChanges: 'حفظ التغييرات',
      
      // Add new translations for the assigned tasks view
      myAssignedTasks: 'مهامي المُسندة',
      myAssignedTasksDesc: 'عرض وتحديث جميع المهام المخصصة لك',
      assignedTasksTable: 'جدول المهام المخصصة',
      noAssignedTasks: 'لا توجد مهام مخصصة لك حالياً',
      markAsComplete: 'وضع علامة مكتمل',
      viewDetails: 'عرض التفاصيل',
      attachFile: 'إرفاق ملف',
      addComment: 'إضافة تعليق',
      markAsBlocked: 'وضع علامة معاق',
      updateTaskStatus: 'تحديث حالة المهمة',
      taskCompletion: 'نسبة إكمال المهمة',
      statusUpdateNote: 'ملاحظة تحديث الحالة',
      addNoteAboutThisUpdate: 'أضف ملاحظة حول هذا التحديث',
      markingAsComplete: 'وضع علامة مكتمل على المهمة',
      completeTaskNotification: 'سيتم إخطار الموظف ومسؤول التأهيل بأنك أكملت هذه المهمة.',
      updateStatus: 'تحديث الحالة',
      blocked: 'معاق',
      assignedTasks: 'المهام المُسندة',
      export: 'تصدير',
      exportCSV: 'تصدير إلى CSV',
      exportPDF: 'تصدير إلى PDF',
    },
    
    // Add new translations for the My Tasks section
    en: {
      // ... existing translations ...
      
      myTasks: 'My Tasks',
      manageYourAssignedOnboardingTasks: 'Manage all tasks assigned to you across different onboarding processes',
    },
    
    ar: {
      // ... existing translations ...
      
      myTasks: 'مهامي',
      manageYourAssignedOnboardingTasks: 'إدارة جميع المهام المخصصة لك عبر عمليات التأهيل المختلفة',
    },
    
    // Add new translations for task type specific fields
    en: {
      // ... existing translations ...
      
      // Document Task Type
      documentDetails: 'Document Details',
      documentType: 'Document Type',
      identificationDocuments: 'Identification Documents',
      employmentContract: 'Employment Contract',
      financialDocuments: 'Financial Documents',
      educationalCertificates: 'Educational Certificates',
      medicalRecords: 'Medical Records',
      verificationFlow: 'Verification Flow',
      standardVerification: 'Standard Verification',
      expressVerification: 'Express Verification',
      externalVerification: 'External Verification',
      requiredSignatures: 'Required Signatures',
      documentOptions: 'Document Options',
      needsNotarization: 'Needs Notarization',
      needsTranslation: 'Needs Translation',
      confidentialDocument: 'Confidential Document',
      documentTemplateAvailable: 'Document template is available for this task',
      viewTemplate: 'View Template',
      
      // Meeting Task Type
      meetingDetails: 'Meeting Details',
      meetingDuration: 'Duration (minutes)',
      enterDurationInMinutes: 'Enter duration in minutes',
      minutes: 'minutes',
      meetingTime: 'Meeting Time',
      selectTime: 'Select time',
      meetingType: 'Meeting Type',
      virtual: 'Virtual',
      inPerson: 'In Person',
      hybrid: 'Hybrid',
      meetingLink: 'Meeting Link',
      enterMeetingLink: 'Enter virtual meeting link',
      meetingLocation: 'Meeting Location',
      enterPhysicalLocation: 'Enter physical location',
      meetingAgenda: 'Agenda',
      enterMeetingAgenda: 'Enter meeting agenda items',
      additionalMeetingOptions: 'Additional Options',
      sendCalendarInvite: 'Send Calendar Invite',
      recordMeeting: 'Record Meeting',
      requiresPreparation: 'Requires Preparation',
      
      // Tech Setup Task Type
      techSetupDetails: 'Tech Setup Details',
      hardwareRequirements: 'Hardware Requirements',
      laptop: 'Laptop/Computer',
      monitor: 'Monitor/Display',
      keyboard: 'Keyboard',
      mouse: 'Mouse/Pointing Device',
      headset: 'Headset/Microphone',
      phone: 'Phone/Communication Device',
      additionalHardware: 'Additional Hardware',
      specifyAdditionalHardware: 'Specify additional hardware needed',
      softwareRequirements: 'Software Requirements',
      emailSetup: 'Email Setup',
      vpnAccess: 'VPN Access',
      messagingTools: 'Messaging Tools (e.g., Teams, Slack)',
      cloudStorage: 'Cloud Storage',
      companyERP: 'Company ERP Access',
      companyCRM: 'Company CRM Access',
      additionalSoftware: 'Additional Software',
      specifyAdditionalSoftware: 'Specify any additional software or tools required',
      accessPermissions: 'Access Permissions',
      accessLevel: 'Access Level',
      basicAccess: 'Basic Access',
      standardAccess: 'Standard Access',
      elevatedAccess: 'Elevated Access',
      adminAccess: 'Admin Access',
      networkDrives: 'Shared Drives Access',
      databases: 'Database Access',
      servers: 'Server Access',
      accessRequiresApproval: '🔒 Elevated access requires manager approval',
      itRequestPriority: 'IT Request Priority',
      withinOneWeek: 'Within one week',
      within48Hours: 'Within 48 hours',
      within24Hours: 'Within 24 hours',
      immediate: 'Immediate attention',
      
      // Manual Task Type
      manualTaskDetails: 'Manual Task Details',
      taskCategory: 'Task Category',
      paperwork: 'Paperwork',
      facilityAccess: 'Facility Access',
      officeSupplies: 'Office Supplies',
      transportation: 'Transportation',
      other: 'Other',
      estimatedDuration: 'Estimated Duration',
      enterDuration: 'Enter duration',
      physicalLocation: 'Physical Location',
      mainOffice: 'Main Office',
      branchOffice1: 'Branch Office - East',
      branchOffice2: 'Branch Office - West',
      warehouse: 'Warehouse',
      otherLocation: 'Other Location',
      stepByStepInstructions: 'Step-by-step Instructions',
      enterInstructions: 'Enter detailed instructions',
      completionVerification: 'Completion Verification',
      selfReported: 'Self-reported Completion',
      managerApproval: 'Manager Approval',
      photoEvidence: 'Photo Evidence',
      documentUpload: 'Document Upload',
      manualTaskRequiresInPersonPresence: 'This task requires in-person presence at the location',
      
      // Video Task Type
      videoTrainingDetails: 'Video Training Details',
      videoTitle: 'Video Title',
      enterVideoTitle: 'Enter video title',
      videoDuration: 'Video Duration',
      enterVideoDuration: 'Enter duration',
      videoCategory: 'Video Category',
      companyOrientation: 'Company Orientation',
      complianceTraining: 'Compliance Training',
      softwareTraining: 'Software Training',
      safetyTraining: 'Safety Training',
      productTraining: 'Product Training',
      videoSource: 'Video Source',
      internalLibrary: 'Internal Library',
      externalLink: 'External Link',
      learningManagementSystem: 'Learning Management System',
      internalVideo: 'Internal Video',
      selectFromLibrary: 'Select from library',
      companyIntroduction: 'Company Introduction',
      companyPolicies: 'Company Policies',
      safetyProcedures: 'Safety Procedures',
      companySystems: 'Company Systems',
      companyValues: 'Company Values',
      videoURL: 'Video URL',
      enterVideoLink: 'Enter video link',
      courseCode: 'Course Code',
      enterCourseCode: 'Enter course code',
      moduleNumber: 'Module Number',
      enterModuleNumber: 'Enter module number',
      completionRequirements: 'Completion Requirements',
      completionQuiz: 'Completion Quiz',
      requiresCertificate: 'Requires Certificate',
      trackWatchTime: 'Track Watch Time',
      quizWillBeRequiredAfterVideo: 'A quiz will be required after watching the video',
      setupQuiz: 'Setup Quiz',
      
      // Toggle additional fields
      hideDetails: 'Hide Details',
      showDetails: 'Show Details',
    },
    
    ar: {
      // ... existing translations ...
      
      // Document Task Type
      documentDetails: 'تفاصيل المستند',
      documentType: 'نوع المستند',
      identificationDocuments: 'وثائق الهوية',
      employmentContract: 'عقد العمل',
      financialDocuments: 'المستندات المالية',
      educationalCertificates: 'الشهادات التعليمية',
      medicalRecords: 'السجلات الطبية',
      verificationFlow: 'مسار التحقق',
      standardVerification: 'التحقق القياسي',
      expressVerification: 'التحقق السريع',
      externalVerification: 'التحقق الخارجي',
      requiredSignatures: 'التوقيعات المطلوبة',
      documentOptions: 'خيارات المستند',
      needsNotarization: 'يحتاج إلى توثيق',
      needsTranslation: 'يحتاج إلى ترجمة',
      confidentialDocument: 'مستند سري',
      documentTemplateAvailable: 'نموذج المستند متاح لهذه المهمة',
      viewTemplate: 'عرض النموذج',
      
      // Meeting Task Type
      meetingDetails: 'تفاصيل الاجتماع',
      meetingDuration: 'المدة (بالدقائق)',
      enterDurationInMinutes: 'أدخل المدة بالدقائق',
      minutes: 'دقائق',
      meetingTime: 'وقت الاجتماع',
      selectTime: 'حدد الوقت',
      meetingType: 'نوع الاجتماع',
      virtual: 'افتراضي',
      inPerson: 'حضوري',
      hybrid: 'مختلط',
      meetingLink: 'رابط الاجتماع',
      enterMeetingLink: 'أدخل رابط الاجتماع الافتراضي',
      meetingLocation: 'موقع الاجتماع',
      enterPhysicalLocation: 'أدخل الموقع الفعلي',
      meetingAgenda: 'جدول أعمال',
      enterMeetingAgenda: 'أدخل بنود جدول الأعمال',
      additionalMeetingOptions: 'خيارات إضافية',
      sendCalendarInvite: 'إرسال دعوة التقويم',
      recordMeeting: 'تسجيل الاجتماع',
      requiresPreparation: 'يتطلب تحضير',
      
      // Tech Setup Task Type
      techSetupDetails: 'تفاصيل الإعداد التقني',
      hardwareRequirements: 'متطلبات الأجهزة',
      laptop: 'الحاسوب المحمول',
      monitor: 'شاشة العرض',
      keyboard: 'لوحة المفاتيح',
      mouse: 'الفأرة',
      headset: 'سماعة الرأس/الميكروفون',
      phone: 'الهاتف/جهاز الاتصال',
      additionalHardware: 'أجهزة إضافية',
      specifyAdditionalHardware: 'حدد الأجهزة الإضافية المطلوبة',
      softwareRequirements: 'متطلبات البرمجيات',
      emailSetup: 'إعداد البريد الإلكتروني',
      vpnAccess: 'الوصول إلى VPN',
      messagingTools: 'أدوات المراسلة (مثل Teams، Slack)',
      cloudStorage: 'التخزين السحابي',
      companyERP: 'الوصول إلى نظام تخطيط موارد الشركة',
      companyCRM: 'الوصول إلى نظام إدارة علاقات العملاء',
      additionalSoftware: 'برمجيات إضافية',
      specifyAdditionalSoftware: 'حدد أي برامج أو أدوات إضافية مطلوبة',
      accessPermissions: 'أذونات الوصول',
      accessLevel: 'مستوى الوصول',
      basicAccess: 'وصول أساسي',
      standardAccess: 'وصول قياسي',
      elevatedAccess: 'وصول متقدم',
      adminAccess: 'وصول المسؤول',
      networkDrives: 'الوصول إلى محركات الأقراص المشتركة',
      databases: 'الوصول إلى قواعد البيانات',
      servers: 'الوصول إلى الخوادم',
      accessRequiresApproval: '🔒 يتطلب الوصول المرتفع موافقة المدير',
      itRequestPriority: 'أولوية طلب تكنولوجيا المعلومات',
      withinOneWeek: 'خلال أسبوع واحد',
      within48Hours: 'خلال 48 ساعة',
      within24Hours: 'خلال 24 ساعة',
      immediate: 'اهتمام فوري',
      
      // Manual Task Type
      manualTaskDetails: 'تفاصيل المهمة اليدوية',
      taskCategory: 'فئة المهمة',
      paperwork: 'وراق',
      facilityAccess: 'وصول المنشأة',
      officeSupplies: 'مستلزمات المكتب',
      transportation: 'النقل',
      other: 'أخرى',
      estimatedDuration: 'المدة المقدرة',
      enterDuration: 'أدخل المدة',
      physicalLocation: 'الموقع الفعلي',
      mainOffice: 'المكتب الرئيسي',
      branchOffice1: 'المكتب الفرعي - الشرق',
      branchOffice2: 'المكتب الفرعي - الغرب',
      warehouse: 'المستودع',
      otherLocation: 'موقع آخر',
      stepByStepInstructions: 'تعليمات خطوة بخطوة',
      enterInstructions: 'أدخل تعليمات مفصلة',
      completionVerification: 'التحقق من الإكمال',
      selfReported: 'إبلاغ ذاتي بالإكمال',
      managerApproval: 'موافقة المدير',
      photoEvidence: 'دليل بالصور',
      documentUpload: 'رفع المستندات',
      manualTaskRequiresInPersonPresence: 'تتطلب هذه المهمة الحضور الشخصي',
      
      // Video Task Type
      videoTrainingDetails: 'تفاصيل التدريب بالفيديو',
      videoTitle: 'عنوان الفيديو',
      enterVideoTitle: 'أدخل عنوان الفيديو',
      videoDuration: 'مدة الفيديو',
      enterVideoDuration: 'أدخل المدة',
      videoCategory: 'فئة الفيديو',
      companyOrientation: 'التوجيه',
      complianceTraining: 'تدريب الامتثال',
      softwareTraining: 'تدريب البرمجيات',
      safetyTraining: 'تدريب السلامة',
      productTraining: 'تدريب المنتج',
      videoSource: 'مصدر الفيديو',
      internalLibrary: 'المكتبة الداخلية',
      externalLink: 'رابط خارجي',
      learningManagementSystem: 'نظام إدارة التعلم',
      internalVideo: 'فيديو داخلي',
      selectFromLibrary: 'اختر من المكتبة',
      companyIntroduction: 'مقدمة الشركة',
      companyPolicies: 'سياسات الشركة',
      safetyProcedures: 'إجراءات السلامة',
      companySystems: 'أنظمة الشركة',
      companyValues: 'قيم الشركة',
      videoURL: 'رابط الفيديو',
      enterVideoLink: 'أدخل رابط الفيديو',
      courseCode: 'رمز الدورة',
      enterCourseCode: 'أدخل رمز الدورة',
      moduleNumber: 'رقم الوحدة',
      enterModuleNumber: 'أدخل رقم الوحدة',
      completionRequirements: 'متطلبات الإكمال',
      completionQuiz: 'اختبار الإكمال',
      requiresCertificate: 'يتطلب شهادة',
      trackWatchTime: 'تتبع وقت المشاهدة',
      quizWillBeRequiredAfterVideo: 'سيكون هناك اختبار مطلوب بعد مشاهدة الفيديو',
      setupQuiz: 'إعداد الاختبار',
      
      // Toggle additional fields
      hideDetails: 'إخفاء التفاصيل',
      showDetails: 'عرض التفاصيل',
    },
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  direction: 'ltr',
  changeLanguage: () => {},
  t: (key: string) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const app = useAppContext();
  const language = app.language as Language;
  const direction = app.direction as Direction;
  const changeLanguage = (lang: Language) => app.setLanguage(lang);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  useEffect(() => {
    document.documentElement.setAttribute('dir', direction);
  }, [direction]);

  return (
    <LanguageContext.Provider value={{ language, direction, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);