import React, { createContext, useContext } from "react";
import { useAppContext } from "../../../../../context/app-context";

type Language = "en" | "ar";
type Direction = "ltr" | "rtl";

interface LanguageContextType {
  language: Language;
  direction: Direction;
  toggleLanguage: () => void;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  direction: "ltr",
  toggleLanguage: () => {},
  setLanguage: () => {},
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { language, direction, setLanguage } = useAppContext();
  const toggleLanguage = () => setLanguage(language === "en" ? "ar" : "en");
  const dict: Record<string, { en: string; ar: string }> = {
    offer: { en: "Offer", ar: "العروض" },
    new_offer: { en: "New Offer", ar: "عرض جديد" },
    content_coming_soon: { en: "Content coming soon", ar: "المحتوى قادم قريباً" },
    analytics: { en: "Analytics", ar: "التحليلات" },
    job_requisition: { en: "Job Requisition", ar: "طلبات الوظائف" },
    candidate: { en: "Candidate", ar: "المرشحين" },
    interview: { en: "Interview", ar: "المقابلة" },
    onboarding: { en: "Onboarding", ar: "التأهيل" },
    careers_portal_setup: { en: "Careers Portal Setup", ar: "إعداد بوابة الوظائف" },
    welcome: { en: "Welcome to Wise", ar: "مرحبًا بك في وايز" },
    total_offers: { en: "Total Offers", ar: "إجمالي العروض" },
    offers_sent: { en: "Offers Sent", ar: "العروض المرسلة" },
    offers_signed: { en: "Offers Signed", ar: "العروض الموقعة" },
    offers_declined: { en: "Expired / Declined", ar: "منتهية/مرفوضة" },
    ai_insights: { en: "AI Insights", ar: "رؤى الذكاء الاصطناعي" },
    common_approval_blockers: { en: "Common Approval Blockers", ar: "أكثر معوقات الموافقة" },
    top_negotiation_requests: { en: "Top Negotiation Requests", ar: "أبرز طلبات التفاوض" },
    average_time_to_sign: { en: "Average Time to Sign", ar: "متوسط وقت التوقيع" },
    days: { en: "days", ar: "أيام" },
    view_detailed_analytics: { en: "View detailed analytics", ar: "عرض التحليلات التفصيلية" },
    // Filters / search / controls
    search_offers: { en: "Search offers", ar: "ابحث في العروض" },
    search_by_candidate_or_title: { en: "Search by candidate or job title", ar: "ابحث بالمرشح أو المسمى الوظيفي" },
    select_status: { en: "Select status", ar: "اختر الحالة" },
    all_statuses: { en: "All statuses", ar: "كل الحالات" },
    more_filters: { en: "More filters", ar: "مزيد من الفلاتر" },
    reset: { en: "Reset", ar: "إعادة تعيين" },
    date_range: { en: "Date range", ar: "نطاق التاريخ" },
    creator: { en: "Creator", ar: "المنشئ" },
    department: { en: "Department", ar: "القسم" },
    save_as_draft: { en: "Save as draft", ar: "حفظ كمسودة" },

    // Generic / table
    name: { en: "Name", ar: "الاسم" },
    actions: { en: "Actions", ar: "الإجراءات" },
    move_up: { en: "Move up", ar: "تحريك لأعلى" },
    move_down: { en: "Move down", ar: "تحريك لأسفل" },
    remove: { en: "Remove", ar: "إزالة" },
    status: { en: "Status", ar: "الحالة" },
    pending: { en: "Pending", ar: "معلق" },
    approved: { en: "Approved", ar: "معتمد" },
    rejected: { en: "Rejected", ar: "مرفوض" },
    sent: { en: "Sent", ar: "تم الإرسال" },
    signed: { en: "Signed", ar: "موقَّع" },
    declined: { en: "Declined", ar: "مرفوض" },
    draft: { en: "Draft", ar: "مسودة" },
    pending_approval: { en: "Pending approval", ar: "بانتظار الموافقة" },
    expired: { en: "Expired", ar: "منتهي" },
    cancel: { en: "Cancel", ar: "إلغاء" },
    next: { en: "Next", ar: "التالي" },
    back: { en: "Back", ar: "رجوع" },
    details: { en: "Details", ar: "التفاصيل" },
    history: { en: "History", ar: "السجل" },
    communication: { en: "Communication", ar: "التواصل" },
    documents: { en: "Documents", ar: "المستندات" },
    view: { en: "View", ar: "عرض" },
    download: { en: "Download", ar: "تنزيل" },
    duplicate: { en: "Duplicate", ar: "نسخ" },
    edit: { en: "Edit", ar: "تعديل" },
    no_offer_selected: { en: "No offer selected", ar: "لم يتم اختيار عرض" },
    back_to_list: { en: "Back to list", ar: "العودة إلى القائمة" },
    offers_table: { en: "Offers table", ar: "جدول العروض" },
    updated_date: { en: "Updated date", ar: "تاريخ التحديث" },
    view_details: { en: "View details", ar: "عرض التفاصيل" },
    more_actions: { en: "More actions", ar: "إجراءات أخرى" },
    confirm_delete_offer: { en: "Delete this offer?", ar: "هل تريد حذف هذا العرض؟" },
    delete: { en: "Delete", ar: "حذف" },
    no_offers_found: { en: "No offers found", ar: "لا توجد عروض" },

    // Wizard steps
    offer_setup: { en: "Offer setup", ar: "إعداد العرض" },
    offer_letter: { en: "Offer letter", ar: "خطاب العرض" },
    approval_workflow: { en: "Approval workflow", ar: "سير الموافقات" },
    send_to_candidate: { en: "Send to candidate", ar: "إرسال إلى المرشح" },
    signature: { en: "Signature", ar: "التوقيع" },
    ai_assistant: { en: "AI Assistant", ar: "مساعد الذكاء الاصطناعي" },
    ai_assistant_message: { en: "Let AI help you compose and validate your offer", ar: "دع الذكاء الاصطناعي يساعدك في صياغة والتحقق من العرض" },
    confirm_cancel_wizard: { en: "Discard this offer and exit the wizard?", ar: "هل تريد إلغاء هذا العرض والخروج من المعالج؟" },
    complete: { en: "Complete", ar: "إكمال" },

    // Fields / labels / placeholders
    basic_information: { en: "Basic information", ar: "المعلومات الأساسية" },
    job_requisition: { en: "Job requisition", ar: "طلب الوظيفة" },
    select_requisition: { en: "Select requisition", ar: "اختر طلب الوظيفة" },
    candidate: { en: "Candidate", ar: "المرشح" },
    select_candidate: { en: "Select candidate", ar: "اختر المرشح" },
    job_details: { en: "Job details", ar: "تفاصيل الوظيفة" },
    job_title: { en: "Job title", ar: "المسمى الوظيفي" },
    job_title_placeholder: { en: "Job title", ar: "المسمى الوظيفي" },
    department_placeholder: { en: "Department", ar: "القسم" },
    grade_placeholder: { en: "Grade", ar: "الدرجة" },
    grade: { en: "Grade", ar: "الدرجة" },

    compensation_and_benefits: { en: "Compensation and benefits", ar: "الرواتب والمزايا" },
    base_salary_sar: { en: "Base salary (SAR)", ar: "الراتب الأساسي (ريال)" },
    housing_allowance_sar: { en: "Housing allowance (SAR)", ar: "بدل السكن (ريال)" },
    transportation_allowance_sar: { en: "Transportation allowance (SAR)", ar: "بدل المواصلات (ريال)" },
    other_allowances_sar: { en: "Other allowances (SAR)", ar: "بدلات أخرى (ريال)" },
    ai_suggested_compensation: { en: "AI suggested compensation", ar: "تعويض مقترح من الذكاء الاصطناعي" },
    total_package: { en: "Total package", ar: "إجمالي الحزمة" },
    ai_suggestion_based_on: { en: "Suggestion is based on market and internal parity", ar: "الاقتراح مبني على السوق والتكافؤ الداخلي" },

    contract_type: { en: "Contract type", ar: "نوع العقد" },
    select_contract_type: { en: "Select contract type", ar: "اختر نوع العقد" },
    probation_period_months: { en: "Probation period (months)", ar: "فترة التجربة (أشهر)" },
    working_hours: { en: "Working hours", ar: "ساعات العمل" },
    working_hours_placeholder: { en: "e.g. 8:00–17:00 Sun–Thu", ar: "مثال: 8:00–17:00 الأحد–الخميس" },

    approval_workflow_required: { en: "Approval workflow required", ar: "يلزم سير موافقات" },
    approval_workflow_instructions: { en: "Configure the approvers for this offer.", ar: "قم بإعداد المعتمدين لهذا العرض." },
    add_approvers: { en: "Add approvers", ar: "إضافة معتمدين" },
    select_approver: { en: "Select approver", ar: "اختر المعتمد" },
    select_from_common_approvers: { en: "Select from common approvers", ar: "اختر من المعتمدين الشائعين" },
    approver_name: { en: "Approver name", ar: "اسم المعتمد" },
    enter_name: { en: "Enter name", ar: "أدخل الاسم" },
    position: { en: "Position", ar: "المنصب" },
    enter_position: { en: "Enter position", ar: "أدخل المنصب" },
    approval_templates: { en: "Approval templates", ar: "قوالب الموافقة" },
    approval_chain: { en: "Approval chain", ar: "سلسلة الموافقات" },
    no_approvers_added: { en: "No approvers added", ar: "لم تتم إضافة معتمدين" },
    add_approvers_instruction: { en: "Add approvers in order. Each approver will be notified to review.", ar: "أضف المعتمدين بالترتيب. سيتم إشعار كل معتمد للمراجعة." },
    add_approver: { en: "Add approver", ar: "إضافة معتمد" },
    approvers_table: { en: "Approvers table", ar: "جدول المعتمدين" },
    standard_approval_flow: { en: "Standard approval flow", ar: "سير موافقات قياسي" },
    executive_approval_flow: { en: "Executive approval flow", ar: "سير موافقات تنفيذي" },
    ai_approval_recommendation: { en: "AI approval recommendation", ar: "توصية الموافقة بالذكاء الاصطناعي" },
    ai_recommends_approval_chain: { en: "AI recommends the current approval chain.", ar: "يوصي الذكاء الاصطناعي بسلسلة الموافقات الحالية." },

    offer_letter_instructions: { en: "Provide the English and Arabic versions of the offer letter.", ar: "قدم نسختين عربية وإنجليزية من خطاب العرض." },
    english_version: { en: "English version", ar: "النسخة الإنجليزية" },
    arabic_version: { en: "Arabic version", ar: "النسخة العربية" },
    english_offer_letter_template: { en: "English offer letter template", ar: "قالب خطاب العرض الإنجليزي" },
    arabic_offer_letter_template: { en: "Arabic offer letter template", ar: "قالب خطاب العرض العربي" },
    template_valid: { en: "Template is valid", ar: "القالب صالح" },
    preview_pdf: { en: "Preview PDF", ar: "معاينة PDF" },
    saudi_labor_law_compliance: { en: "Complies with Saudi labor law", ar: "يتوافق مع نظام العمل السعودي" },
    compliance_status: { en: "Compliance status", ar: "حالة الامتثال" },
    compliant_with_saudi_labor_law: { en: "Compliant with Saudi Labor Law", ar: "متوافق مع نظام العمل السعودي" },
    required_clauses: { en: "Required clauses", ar: "البنود المطلوبة" },
    iqama_clause: { en: "Iqama clause", ar: "بند الإقامة" },
    gosi: { en: "GOSI", ar: "التأمينات الاجتماعية" },
    probation: { en: "Probation", ar: "فترة التجربة" },

    // Communication & email
    communication_channel: { en: "Communication channel", ar: "قناة التواصل" },
    select_communication_channel: { en: "Select communication channel", ar: "اختر قناة التواصل" },
    email: { en: "Email", ar: "البريد الإلكتروني" },
    whatsapp: { en: "WhatsApp", ar: "واتساب" },
    sms: { en: "SMS", ar: "رسالة نصية" },
    careers_portal: { en: "Careers portal", ar: "بوابة الوظائف" },
    email_address: { en: "Email address", ar: "عنوان البريد الإلكتروني" },
    enter_email_address: { en: "Enter email address", ar: "أدخل عنوان البريد الإلكتروني" },
    email_subject: { en: "Email subject", ar: "موضوع البريد الإلكتروني" },
    enter_subject: { en: "Enter subject", ar: "أدخل الموضوع" },
    email_body: { en: "Email body", ar: "نص البريد الإلكتروني" },
    enter_message: { en: "Enter message", ar: "أدخل الرسالة" },
    phone_number: { en: "Phone number", ar: "رقم الجوال" },
    message: { en: "Message", ar: "رسالة" },
    portal_notification_description: { en: "Candidate will receive a notification in the careers portal.", ar: "سيتلقى المرشح إشعارًا في بوابة الوظائف." },
    allow_candidate_negotiation: { en: "Allow candidate negotiation", ar: "السماح بتفاوض المرشح" },
    salary: { en: "Salary", ar: "الراتب" },
    start_date: { en: "Start date", ar: "تاريخ البدء" },
    benefits: { en: "Benefits", ar: "المزايا" },
    negotiation_options: { en: "Negotiation options", ar: "خيارات التفاوض" },
    ready_to_send: { en: "Ready to send", ar: "جاهز للإرسال" },
    ready_to_send_description: { en: "All required fields are complete and the offer is ready to be sent.", ar: "جميع الحقول المطلوبة مكتملة والعرض جاهز للإرسال." },
    send_offer: { en: "Send offer", ar: "إرسال العرض" },

    // AI communication card (create new offer)
    ai_communication: { en: "AI communication", ar: "تواصل الذكاء الاصطناعي" },
    ai_communication_analysis: { en: "AI communication analysis", ar: "تحليل تواصل الذكاء الاصطناعي" },
    ai_communication_suggestion: { en: "AI suggests optimizing the tone for better acceptance rates.", ar: "يقترح الذكاء الاصطناعي تحسين النبرة لزيادة معدلات القبول." },

    // Enumerations
    permanent: { en: "Permanent", ar: "دائم" },
    temporary: { en: "Temporary", ar: "مؤقت" },
    contract: { en: "Contract", ar: "عقد" },

    // Offer details page
    offer_information: { en: "Offer information", ar: "معلومات العرض" },
    offer_id: { en: "Offer ID", ar: "معرّف العرض" },
    created_date: { en: "Created date", ar: "تاريخ الإنشاء" },
    created_by: { en: "Created by", ar: "تم الإنشاء بواسطة" },
    candidate_name: { en: "Candidate name", ar: "اسم المرشح" },
    compensation_details: { en: "Compensation details", ar: "تفاصيل التعويضات" },
    base_salary: { en: "Base salary", ar: "الراتب الأساسي" },
    housing_allowance: { en: "Housing allowance", ar: "بدل السكن" },
    transportation_allowance: { en: "Transportation allowance", ar: "بدل النقل" },
    other_allowances: { en: "Other allowances", ar: "بدلات أخرى" },
    total_monthly_compensation: { en: "Total monthly compensation", ar: "إجمالي التعويض الشهري" },
    bonuses: { en: "Bonuses", ar: "المكافآت" },
    probation_period: { en: "Probation period", ar: "فترة التجربة" },
    months: { en: "months", ar: "أشهر" },
    view_documents: { en: "View documents", ar: "عرض المستندات" },
    upload_document: { en: "Upload document", ar: "رفع مستند" },
    offer_letter_english: { en: "Offer letter (English)", ar: "خطاب العرض (إنجليزي)" },
    offer_letter_arabic: { en: "Offer letter (Arabic)", ar: "خطاب العرض (عربي)" },
    signed_offer_letter: { en: "Signed offer letter", ar: "خطاب العرض الموقّع" },
    pdf_document: { en: "PDF document", ar: "مستند PDF" },
    portal: { en: "Portal", ar: "البوابة" },
    no_communication_history: { en: "No communication history", ar: "لا يوجد سجل تواصل" },
    sent_to_candidate: { en: "Sent to candidate", ar: "تم الإرسال إلى المرشح" },
    received_from_candidate: { en: "Received from candidate", ar: "تم الاستلام من المرشح" },
    event_created: { en: "Created", ar: "تم الإنشاء" },
    event_edited: { en: "Edited", ar: "تم التعديل" },
    event_approved: { en: "Approved", ar: "تمت الموافقة" },
    event_rejected: { en: "Rejected", ar: "تم الرفض" },
    event_sent: { en: "Sent", ar: "تم الإرسال" },
    event_signed: { en: "Signed", ar: "تم التوقيع" },
    event_declined: { en: "Declined", ar: "تم الرفض" },

    // Attachments & settings
    offer_settings: { en: "Offer settings", ar: "إعدادات العرض" },
    attachments: { en: "Attachments", ar: "المرفقات" },
    offer_letter_en_ar: { en: "Offer letter (EN/AR)", ar: "خطاب العرض (إنجليزي/عربي)" },
    bilingual_pdf_description: { en: "A single PDF containing English and Arabic versions.", ar: "ملف PDF واحد يحتوي على النسختين الإنجليزية والعربية." },
    expiration: { en: "Expiration", ar: "الانتهاء" },
    offer_expiry_date: { en: "Offer expiry date", ar: "تاريخ انتهاء العرض" },
    "mm/dd/yyyy": { en: "MM/DD/YYYY", ar: "شهر/يوم/سنة" },

    // DocuSign / signature
    signature_method: { en: "Signature method", ar: "طريقة التوقيع" },
    docusign_configuration: { en: "DocuSign configuration", ar: "إعدادات DocuSign" },
    docusign_account_connected: { en: "DocuSign account connected", ar: "تم ربط حساب DocuSign" },
    docusign_account_email: { en: "Account email", ar: "بريد الحساب" },
    docusign_recipients: { en: "Recipients", ar: "المستلمون" },
    recipient_name: { en: "Recipient name", ar: "اسم المستلم" },
    recipient_email: { en: "Recipient email", ar: "بريد المستلم" },
    recipient_role: { en: "Recipient role", ar: "دور المستلم" },
    signer: { en: "Signer", ar: "الموقّع" },
    docusign_document_settings: { en: "Document settings", ar: "إعدادات المستند" },
    document_language: { en: "Document language", ar: "لغة المستند" },
    match_recipient_language: { en: "Match recipient language", ar: "مطابقة لغة المستلم" },
    expiration_period: { en: "Expiration period", ar: "فترة الانتهاء" },
    "14_days": { en: "14 days", ar: "14 يوماً" },
    reminder_frequency: { en: "Reminder frequency", ar: "تكرار التذكير" },
    every_3_days: { en: "Every 3 days", ar: "كل 3 أيام" },
    email_notification: { en: "Email notification", ar: "إشعار بالبريد الإلكتروني" },
    email_message: { en: "Email message", ar: "رسالة البريد الإلكتروني" },
    docusign_integration_info: { en: "DocuSign integration", ar: "تكامل DocuSign" },
    docusign_integration_details: { en: "Connect your DocuSign account to send and track signatures.", ar: "اربط حساب DocuSign لإرسال وتتبع التوقيعات." },
    signature_status_tracking: { en: "Signature status tracking", ar: "تتبّع حالة التوقيع" },
    sent_date: { en: "Sent date", ar: "تاريخ الإرسال" },
    signed_date: { en: "Signed date", ar: "تاريخ التوقيع" },
    documents: { en: "Documents", ar: "المستندات" },
    signature_status_will_update: { en: "Signature status will update automatically.", ar: "سيتم تحديث حالة التوقيع تلقائياً." },
    preview_documents: { en: "Preview documents", ar: "معاينة المستندات" },
    send_via_docusign: { en: "Send via DocuSign", ar: "إرسال عبر DocuSign" },

    // Subject/body helpers and fallbacks
    offer_letter_subject_prefix: { en: "Offer Letter for", ar: "خطاب عرض لوظيفة" },
    dear: { en: "Dear", ar: "عزيزي" },
    we_are_pleased_to_offer_you: { en: "We are pleased to offer you the position of {jobTitle} at our company. Please find attached your official offer letter with all the details regarding the position, compensation, and benefits.", ar: "يسعدنا أن نقدم لك منصب {jobTitle} في شركتنا. يرجى الاطلاع على خطاب العرض المرفق الذي يحتوي على جميع التفاصيل المتعلقة بالمنصب والتعويضات والمزايا." },
    this_offer_will_remain_valid: { en: "This offer will remain valid until {expiryDate}.", ar: "سيبقى هذا العرض ساريًا حتى {expiryDate}." },
    if_you_have_any_questions: { en: "If you have any questions or wish to discuss any aspects of this offer, please do not hesitate to contact us.", ar: "إذا كانت لديك أي أسئلة أو ترغب في مناقشة أي جانب من جوانب هذا العرض، فلا تتردد في الاتصال بنا." },
    we_look_forward_to_your_positive_response: { en: "We look forward to your positive response and to welcoming you to our team.", ar: "نتطلع إلى ردك الإيجابي والترحيب بك في فريقنا." },
    best_regards: { en: "Best regards,", ar: "مع أطيب التحيات،" },
    your_name: { en: "[Your Name]", ar: "[اسمك]" },
    your_position: { en: "[Your Position]", ar: "[منصبك]" },
    company_name: { en: "[Company Name]", ar: "[اسم الشركة]" },
    job_title_placeholder_fallback: { en: "[Job Title]", ar: "[المسمى الوظيفي]" },
    candidate_name_placeholder_fallback: { en: "[Candidate Name]", ar: "[اسم المرشح]" },
    expiry_date_placeholder_fallback: { en: "[Expiry Date]", ar: "[تاريخ الانتهاء]" },

    // Extra labels used in signature step
    change_account: { en: "Change account", ar: "تغيير الحساب" },
    docusign_account_not_connected: { en: "DocuSign account not connected", ar: "لم يتم ربط حساب DocuSign" },
    docusign_connect_account_instruction: { en: "Connect your DocuSign account to proceed.", ar: "اربط حساب DocuSign للمتابعة." },
    connect_docusign: { en: "Connect DocuSign", ar: "ربط DocuSign" },
    add_recipient: { en: "Add recipient", ar: "إضافة مستلم" },
    carbon_copy: { en: "CC (Carbon copy)", ar: "نسخة كربونية" },
    english: { en: "English", ar: "الإنجليزية" },
    arabic: { en: "Arabic", ar: "العربية" },
    bilingual: { en: "Bilingual", ar: "ثنائي اللغة" },
    '7_days': { en: '7 days', ar: '7 أيام' },
    '30_days': { en: '30 days', ar: '30 يوماً' },
    '60_days': { en: '60 days', ar: '60 يوماً' },
    daily: { en: 'Daily', ar: 'يوميًا' },
    weekly: { en: 'Weekly', ar: 'أسبوعيًا' },
    no_reminders: { en: 'No reminders', ar: 'بدون تذكيرات' },
    include_watermark: { en: 'Include watermark', ar: 'تضمين علامة مائية' },
    adobesign_configuration: { en: 'Adobe Sign configuration', ar: 'إعدادات Adobe Sign' },
    adobesign_instructions: { en: 'Configure Adobe Sign settings and recipients.', ar: 'قم بإعداد إعدادات Adobe Sign والمستلمين.' },
    signature_flow: { en: 'Signature flow', ar: 'سير التوقيع' },
    select_flow: { en: 'Select flow', ar: 'اختر السير' },
    sequential_signing: { en: 'Sequential signing', ar: 'توقيع متسلسل' },
    parallel_signing: { en: 'Parallel signing', ar: 'توقيع متوازي' },
    select_expiration: { en: 'Select expiration', ar: 'اختر مدة الانتهاء' },
    send_for_signature: { en: 'Send for signature', ar: 'إرسال للتوقيع' },
    manual_signature_process: { en: 'Manual signature process', ar: 'عملية توقيع يدوية' },
    manual_signature_instructions: { en: 'Download, print, sign, then upload the signed document.', ar: 'قم بتنزيل المستند ثم طباعته وتوقيعه ثم رفعه.' },
    download_offer_letter: { en: 'Download offer letter', ar: 'تنزيل خطاب العرض' },
    download_print_sign_instructions: { en: 'Download, print and sign the offer letter.', ar: 'قم بتنزيل خطاب العرض وطباعته وتوقيعه.' },
    download_pdf: { en: 'Download PDF', ar: 'تنزيل PDF' },
    upload_signed_document: { en: 'Upload signed document', ar: 'رفع المستند الموقّع' },
    upload_instructions: { en: 'Upload the scanned signed PDF.', ar: 'قم برفع ملف PDF الموقع بالمسح.' },
    upload_signed_file: { en: 'Upload signed file', ar: 'رفع الملف الموقّع' },
    housing: { en: 'Housing', ar: 'السكن' },
    transportation: { en: 'Transportation', ar: 'النقل' },
  };
  const t = (key: string) => (dict[key] ? dict[key][language] : key);
  return (
    <LanguageContext.Provider value={{ language, direction, toggleLanguage, setLanguage, t }}>
        {children}
    </LanguageContext.Provider>
  );
};